begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select plan(1);
set local app.tenant_id='00000000-0000-7000-8000-000000000001';
do $$ declare i uuid;r uuid;person uuid;work uuid;artifact uuid;doc uuid;version uuid;rep uuid;node uuid;procedure uuid;chunkset uuid;chunk uuid;
begin
 insert into orchestration.operation_intent(intent_type,payload,idempotency_key) values('upsert_entity','{}','km-media:'||util.uuidv7()) returning id into i;
 insert into orchestration.operation_receipt(intent_id,executor_version,outcome) values(i,'test','applied') returning id into r;
 insert into corpus.entity(kind,display_name,slug,created_by_receipt_id) values('person','Speaker','km-speaker',r) returning id into person;
 insert into corpus.person(id) values(person);
 insert into corpus.entity(kind,display_name,slug,created_by_receipt_id) values('media_work','Video','km-video',r) returning id into work;
 insert into corpus.media_work(id,media_kind,platform_code,title) values(work,'video','youtube','Video');
 insert into corpus.media_appearance(media_work_id,entity_id,role,start_ms,end_ms,method) values(work,person,'speaker',1000,2000,'manual');
 insert into orchestration.artifact(artifact_type,sha256,bucket_class,storage_bucket,object_path) values('source_capture',repeat('2',64),'source_captures','test','km-media-'||util.uuidv7()) returning id into artifact;
 insert into content.document(document_type_code,canonical_title,work_entity_id) values('video_transcript','Video transcript',work) returning id into doc;
 insert into content.document_version(document_id,version_label,manifest_sha256) values(doc,'1',repeat('2',64)) returning id into version;
 insert into content.document_representation(document_version_id,artifact_id,representation_kind,representation_class,media_type,content_sha256) values(version,artifact,'transcript','faithful_normalization','text/plain',repeat('2',64)) returning id into rep;
 insert into content.document_node(representation_id,ordinal,stable_local_key,node_kind,inline_text,normalized_content_sha256,start_ms,end_ms,speaker_entity_id) values(rep,0,'t1','transcript_segment','Spoken text',repeat('2',64),1000,2000,person) returning id into node;
 insert into retrieval.chunking_procedure_version(slug,version,supported_content_classes,tokenizer,schema_contract,code_sha256,status) values('km-test',1,'["faithful_normalization"]','test','{}',repeat('2',64),'admitted') returning id into procedure;
 insert into retrieval.chunk_set(representation_id,procedure_version_id,frozen_config,tokenizer,input_manifest_sha256,chunk_set_sha256) values(rep,procedure,'{}','test',repeat('2',64),repeat('2',64)) returning id into chunkset;
 insert into retrieval.retrieval_chunk(chunk_set_id,ordinal,source_text,embedding_text,source_text_sha256,contextual_prefix_sha256,embedding_text_sha256,source_token_count,embedding_token_count,retrieval_role) values(chunkset,0,'Spoken text','Spoken text',repeat('2',64),repeat('2',64),repeat('2',64),2,2,'text') returning id into chunk;
 insert into retrieval.chunk_span(chunk_id,ordinal,document_node_id,selected_text_sha256) values(chunk,0,node,repeat('2',64));
 insert into retrieval.chunk_entity_mention(chunk_id,entity_id,verb,method) values(chunk,person,'quotes','manual');
 if not exists(select 1 from retrieval.chunk_entity_mention m join retrieval.chunk_span s on s.chunk_id=m.chunk_id join content.document_node n on n.id=s.document_node_id where m.entity_id=person and n.start_ms=1000 and n.end_ms=2000) then raise exception 'media coordinates lost through chunks';end if;
 if(select count(*) from corpus.media_appearance where media_work_id=work and role='speaker')<>1 then raise exception 'speaker appearance missing';end if;
 set constraints all immediate;
end $$;
select pass('knowledge_model_media invariants hold');
select * from finish();
rollback;
