-- Knowledge model v2: knowledge. See docs/knowledge-model/FINAL-RECOMMENDATION.md.
begin;
set local lock_timeout = '15s';
create table knowledge.record(id uuid primary key default util.uuidv7(),tenant_id uuid not null default util.current_tenant_id(),kind text not null check(kind in ('technical_problem','solution_pattern','advanced_usage_pattern','implementation_example','failure_mode','benchmark_result','compatibility_constraint','operational_practice','security_consideration')),title text not null,statement text not null,scope jsonb not null default '{}',assurance_level text not null default 'asserted' references knowledge.assurance_level(code),provenance_claim_id uuid references evidence.claim(id),created_by_receipt_id uuid not null references orchestration.operation_receipt(id),created_at timestamptz not null default now(),unique(tenant_id,id),unique(tenant_id,id,kind));
create table knowledge.technical_problem(id uuid primary key references knowledge.record(id),tenant_id uuid not null default util.current_tenant_id(),kind text not null default 'technical_problem' check(kind='technical_problem'),problem_class text,symptoms text[],context_of_occurrence text,unique(tenant_id,id),foreign key(tenant_id,id,kind) references knowledge.record(tenant_id,id,kind) deferrable initially deferred);
create table knowledge.solution_pattern(id uuid primary key references knowledge.record(id),tenant_id uuid not null default util.current_tenant_id(),kind text not null default 'solution_pattern' check(kind='solution_pattern'),pattern_kind text,mechanism text,tradeoffs text,unique(tenant_id,id),foreign key(tenant_id,id,kind) references knowledge.record(tenant_id,id,kind) deferrable initially deferred);
create table knowledge.advanced_usage_pattern(id uuid primary key references knowledge.record(id),tenant_id uuid not null default util.current_tenant_id(),kind text not null default 'advanced_usage_pattern' check(kind='advanced_usage_pattern'),prerequisites text[],usage text,unique(tenant_id,id),foreign key(tenant_id,id,kind) references knowledge.record(tenant_id,id,kind) deferrable initially deferred);
create table knowledge.implementation_example(id uuid primary key references knowledge.record(id),tenant_id uuid not null default util.current_tenant_id(),kind text not null default 'implementation_example' check(kind='implementation_example'),repository_file_id uuid references corpus.repository_file(id),symbol text,start_line integer,end_line integer,check(start_line is null or start_line>0),check(end_line is null or end_line>=start_line),unique(tenant_id,id),foreign key(tenant_id,id,kind) references knowledge.record(tenant_id,id,kind) deferrable initially deferred);
create table knowledge.failure_mode(id uuid primary key references knowledge.record(id),tenant_id uuid not null default util.current_tenant_id(),kind text not null default 'failure_mode' check(kind='failure_mode'),failure_class text,trigger_conditions text,mitigations text,unique(tenant_id,id),foreign key(tenant_id,id,kind) references knowledge.record(tenant_id,id,kind) deferrable initially deferred);
create table knowledge.benchmark_result(id uuid primary key references knowledge.record(id),tenant_id uuid not null default util.current_tenant_id(),kind text not null default 'benchmark_result' check(kind='benchmark_result'),benchmark_run_id uuid references corpus.benchmark_run(id),metric_name text,value numeric,unit text,unique(tenant_id,id),foreign key(tenant_id,id,kind) references knowledge.record(tenant_id,id,kind) deferrable initially deferred);
create table knowledge.compatibility_constraint(id uuid primary key references knowledge.record(id),tenant_id uuid not null default util.current_tenant_id(),kind text not null default 'compatibility_constraint' check(kind='compatibility_constraint'),constraint_kind text,expression text,unique(tenant_id,id),foreign key(tenant_id,id,kind) references knowledge.record(tenant_id,id,kind) deferrable initially deferred);
create table knowledge.operational_practice(id uuid primary key references knowledge.record(id),tenant_id uuid not null default util.current_tenant_id(),kind text not null default 'operational_practice' check(kind='operational_practice'),practice_kind text,procedure text,unique(tenant_id,id),foreign key(tenant_id,id,kind) references knowledge.record(tenant_id,id,kind) deferrable initially deferred);
create table knowledge.security_consideration(id uuid primary key references knowledge.record(id),tenant_id uuid not null default util.current_tenant_id(),kind text not null default 'security_consideration' check(kind='security_consideration'),severity text,threat text,mitigation text,unique(tenant_id,id),foreign key(tenant_id,id,kind) references knowledge.record(tenant_id,id,kind) deferrable initially deferred);
create table knowledge.record_entity_link(tenant_id uuid not null default util.current_tenant_id(),record_id uuid not null references knowledge.record(id),entity_id uuid not null references corpus.entity(id),role text not null,primary key(tenant_id,record_id,entity_id,role));
alter table evidence.claim_record add foreign key(record_id) references knowledge.record(id);
alter table taxonomy.assignment add column target_entity_id uuid references corpus.entity(id),add column target_record_id uuid references knowledge.record(id),add check(num_nonnulls(target_entity_id,target_record_id,lesson_id)=1);

create or replace function taxonomy.enforce_term_target_scope() returns trigger language plpgsql set search_path='' as $$
declare actual text;
begin
 if new.target_entity_id is not null then select kind into strict actual from corpus.entity where id=new.target_entity_id and tenant_id=new.tenant_id;
 elsif new.target_record_id is not null then select kind into strict actual from knowledge.record where id=new.target_record_id and tenant_id=new.tenant_id;
 else actual:='lesson';end if;
 if exists(select 1 from taxonomy.term_target_kind where term_id=new.term_id) and not exists(select 1 from taxonomy.term_target_kind where term_id=new.term_id and entity_kind_code=actual) then raise exception 'taxonomy term does not admit target kind' using errcode='23514';end if;return new;
end $$;
create trigger assignment_term_target_scope before insert or update on taxonomy.assignment for each row execute function taxonomy.enforce_term_target_scope();

commit;
