-- Knowledge model v2: evidence. See docs/knowledge-model/FINAL-RECOMMENDATION.md.
begin;
set local lock_timeout = '15s';

alter table evidence.source add column host text,add column registrable_domain text,add column publisher_entity_id uuid references corpus.entity(id),add column source_kind text,
add column first_seen_at timestamptz,add column last_seen_at timestamptz,add column last_encounter_kind text,add column last_capture_id uuid references evidence.source_capture(id),add column capture_count bigint not null default 0,add column failure_streak integer not null default 0,add column next_revisit_after timestamptz,add column blocked_reason text,add column state_knowledge_seq bigint;
insert into evidence.capture_method(code,description) select distinct capture_method,capture_method from evidence.source_capture on conflict do nothing;
alter table evidence.source_capture add foreign key(capture_method) references evidence.capture_method(code);
alter table evidence.locator add column selector_kind text not null default 'text_quote' check(selector_kind in ('text_quote','character_position','multi_fragment_text','json_pointer','html','pdf_text','bounding_box','table','repository','dataset','api_record','media_timecode','media_region')),add column start_ms integer,add column end_ms integer,add column page_number integer,
add check(start_ms is null or start_ms>=0),add check(end_ms is null or(start_ms is not null and end_ms>=start_ms)),add check(selector_kind not in ('media_timecode','media_region') or start_ms is not null);
create table evidence.source_query(id uuid primary key default util.uuidv7(),tenant_id uuid not null default util.current_tenant_id(),provider_code text not null references evidence.search_provider(code),query_text text not null,purpose text not null,parameters jsonb not null default '{}',response_artifact_id uuid references orchestration.artifact(id),attempt_id uuid references orchestration.attempt(id),queried_at timestamptz not null default now(),unique(tenant_id,id));
create table evidence.provider_result(id uuid primary key default util.uuidv7(),tenant_id uuid not null default util.current_tenant_id(),query_id uuid not null references evidence.source_query(id),rank integer not null check(rank>0),source_id uuid references evidence.source(id),url text,title text,snippet text,payload jsonb not null default '{}',artifact_id uuid references orchestration.artifact(id),created_at timestamptz not null default now(),unique(tenant_id,query_id,rank));
create table evidence.source_encounter(id uuid primary key default util.uuidv7(),tenant_id uuid not null default util.current_tenant_id(),source_id uuid not null references evidence.source(id),provider_result_id uuid references evidence.provider_result(id),capture_id uuid references evidence.source_capture(id),encounter_kind text not null check(encounter_kind in ('discovered','captured','unchanged','failed','blocked','revisited')),encountered_at timestamptz not null default now(),details jsonb not null default '{}',receipt_id uuid references orchestration.operation_receipt(id));
create table evidence.extraction_run(id uuid primary key default util.uuidv7(),tenant_id uuid not null default util.current_tenant_id(),representation_id uuid references content.document_representation(id),attempt_id uuid references orchestration.attempt(id),extractor_identity text not null,extractor_version text not null,parameters jsonb not null default '{}',input_digest text not null,result_artifact_id uuid references orchestration.artifact(id),created_at timestamptz not null default now());
create table evidence.extraction_record(id uuid primary key default util.uuidv7(),tenant_id uuid not null default util.current_tenant_id(),extraction_run_id uuid not null references evidence.extraction_run(id),record_kind text not null,payload jsonb not null,locator_id uuid references evidence.locator(id),claim_id uuid references evidence.claim(id),confidence numeric check(confidence between 0 and 1),created_at timestamptz not null default now());
create table evidence.attribution(id uuid primary key default util.uuidv7(),tenant_id uuid not null default util.current_tenant_id(),source_id uuid references evidence.source(id),claim_id uuid references evidence.claim(id),entity_id uuid not null references corpus.entity(id),role text not null,locator_id uuid references evidence.locator(id),extraction_record_id uuid references evidence.extraction_record(id),check(num_nonnulls(source_id,claim_id)>=1));
create table evidence.claim_subject(tenant_id uuid not null default util.current_tenant_id(),claim_id uuid not null references evidence.claim(id),entity_id uuid not null references corpus.entity(id),role text not null check(role in ('subject','object','context')),primary key(tenant_id,claim_id,entity_id,role));
create table evidence.claim_record(tenant_id uuid not null default util.current_tenant_id(),claim_id uuid not null references evidence.claim(id),record_id uuid not null,primary key(tenant_id,claim_id,record_id));
alter table evidence.claim add column relationship_id uuid references corpus.relationship(id);
create table evidence.segment_support(id uuid primary key default util.uuidv7(),tenant_id uuid not null default util.current_tenant_id(),segment_id uuid references temporal.segment(id),event_occurrence_id uuid references temporal.event_occurrence(id),claim_id uuid not null references evidence.claim(id),locator_id uuid not null references evidence.locator(id),role text not null check(role in ('supports','challenges','context')),k_from bigint not null,k_to bigint,check(num_nonnulls(segment_id,event_occurrence_id)=1),check(k_to is null or k_to>k_from));
create trigger stamp_k before insert on evidence.segment_support for each row execute function temporal.stamp_k();
create trigger guard_k before update or delete on evidence.segment_support for each row execute function temporal.guard_k();
create constraint trigger sealed_batch after insert or update on evidence.segment_support deferrable initially deferred for each row execute function temporal.require_sealed_batch();

commit;
