-- Knowledge model v2: teardown. See docs/knowledge-model/FINAL-RECOMMENDATION.md.
begin;
set local lock_timeout = '15s';
-- No CASCADE: unexpected dependents abort deployment. Public/research_private are never altered.
do $$ declare r record; begin
 for r in select p.oid::regprocedure::text signature from pg_proc p where p.pronamespace='api'::regnamespace and (p.prosrc ~ '(corpus|knowledge|ranking|staging)\.' or p.proname='hybrid_knowledge_search_1536') loop execute 'drop function '||r.signature; end loop;
 select string_agg(c.oid::regclass::text,',') as names into r from pg_class c where c.relnamespace='api'::regnamespace and c.relkind='v' and c.relname <> 'mission_progress';
 if r.names is not null then execute 'drop view '||r.names; end if;
end $$;
alter table ranking.group_membership drop constraint group_membership_library_id_fkey;
alter table ranking.group_membership drop constraint group_membership_repository_id_fkey;
alter table ranking.group_membership drop constraint group_membership_person_id_fkey;
alter table ranking.group_membership drop constraint group_membership_organization_id_fkey;
alter table ranking.group_membership drop constraint group_membership_paper_id_fkey;
alter table ranking.group_membership drop constraint group_membership_video_id_fkey;
alter table ranking.group_membership drop constraint group_membership_ai_model_version_id_fkey;
alter table ranking.group_membership drop constraint group_membership_mcp_server_id_fkey;
alter table ranking.group_membership drop constraint group_membership_agent_skill_id_fkey;
alter table ranking.group_membership drop constraint group_membership_product_id_fkey;
alter table retrieval.vector_item drop constraint vector_item_technical_problem_id_fkey;
alter table retrieval.vector_item drop constraint vector_item_solution_pattern_id_fkey;
alter table retrieval.vector_item drop constraint vector_item_advanced_usage_pattern_id_fkey;
alter table retrieval.vector_item drop constraint vector_item_implementation_example_id_fkey;
alter table retrieval.vector_item drop constraint vector_item_failure_mode_id_fkey;
alter table retrieval.vector_item drop constraint vector_item_benchmark_result_id_fkey;
alter table retrieval.vector_item drop constraint vector_item_compatibility_constraint_id_fkey;
alter table retrieval.vector_item drop constraint vector_item_operational_practice_id_fkey;
alter table retrieval.vector_item drop constraint vector_item_security_consideration_id_fkey;
alter table retrieval.vector_item drop constraint vector_item_video_id_fkey;
alter table retrieval.vector_item drop constraint vector_item_talk_id_fkey;
alter table evaluation.review_task drop constraint review_task_candidate_id_fkey;
alter table evaluation.eval_run drop constraint eval_run_metric_definition_version_id_fkey;
alter table evaluation.review_task drop constraint review_task_entity_merge_id_fkey;
alter table evaluation.review_task drop constraint review_task_ranking_result_id_fkey;
alter table curriculum.lesson_covers_concept drop constraint lesson_covers_concept_concept_id_fkey;
alter table curriculum.lesson_backed_by drop constraint lesson_backed_by_technical_problem_id_fkey;
alter table curriculum.lesson_backed_by drop constraint lesson_backed_by_solution_pattern_id_fkey;
alter table curriculum.lesson_backed_by drop constraint lesson_backed_by_advanced_usage_pattern_id_fkey;
alter table curriculum.lesson_backed_by drop constraint lesson_backed_by_implementation_example_id_fkey;
alter table curriculum.lesson_backed_by drop constraint lesson_backed_by_failure_mode_id_fkey;
alter table curriculum.lesson_backed_by drop constraint lesson_backed_by_benchmark_result_id_fkey;
alter table curriculum.lesson_backed_by drop constraint lesson_backed_by_compatibility_constraint_id_fkey;
alter table curriculum.lesson_backed_by drop constraint lesson_backed_by_operational_practice_id_fkey;
alter table curriculum.lesson_backed_by drop constraint lesson_backed_by_security_consideration_id_fkey;
alter table curriculum.challenge_targets drop constraint challenge_targets_concept_id_fkey;
alter table curriculum.challenge_targets drop constraint challenge_targets_library_id_fkey;
alter table curriculum.challenge_targets drop constraint challenge_targets_mcp_server_id_fkey;
alter table curriculum.challenge_targets drop constraint challenge_targets_agent_skill_id_fkey;
alter table curriculum.challenge_targets drop constraint challenge_targets_solution_pattern_id_fkey;
alter table curriculum.challenge_derived_from drop constraint challenge_derived_from_technical_problem_id_fkey;
alter table curriculum.challenge_derived_from drop constraint challenge_derived_from_failure_mode_id_fkey;
alter table curriculum.challenge_derived_from drop constraint challenge_derived_from_implementation_example_id_fkey;
alter table orchestration.capability drop constraint capability_packages_mcp_server_version_fk;
alter table taxonomy.assignment drop constraint assignment_library_id_fkey;
alter table taxonomy.assignment drop constraint assignment_repository_id_fkey;
alter table taxonomy.assignment drop constraint assignment_person_id_fkey;
alter table taxonomy.assignment drop constraint assignment_organization_id_fkey;
alter table taxonomy.assignment drop constraint assignment_paper_id_fkey;
alter table taxonomy.assignment drop constraint assignment_talk_id_fkey;
alter table taxonomy.assignment drop constraint assignment_video_id_fkey;
alter table taxonomy.assignment drop constraint assignment_product_id_fkey;
alter table taxonomy.assignment drop constraint assignment_concept_id_fkey;
alter table taxonomy.assignment drop constraint assignment_ai_model_id_fkey;
alter table taxonomy.assignment drop constraint assignment_ai_protocol_id_fkey;
alter table taxonomy.assignment drop constraint assignment_mcp_server_id_fkey;
alter table taxonomy.assignment drop constraint assignment_agent_skill_id_fkey;
alter table taxonomy.assignment drop constraint assignment_technical_problem_id_fkey;
alter table taxonomy.assignment drop constraint assignment_solution_pattern_id_fkey;
alter table taxonomy.assignment drop constraint assignment_advanced_usage_pattern_id_fkey;
alter table taxonomy.assignment drop constraint assignment_failure_mode_id_fkey;
alter table taxonomy.assignment drop constraint assignment_case_study_id_fkey;
alter table taxonomy.assignment drop constraint assignment_dataset_id_fkey;
alter table taxonomy.assignment drop constraint assignment_benchmark_id_fkey;
alter table retrieval.search_projection drop constraint search_projection_tenant_id_projection_target_id_fkey;
alter table evaluation.eval_case_relevance drop constraint eval_case_relevance_tenant_id_projection_target_id_fkey;
alter table retrieval.packet_member drop constraint packet_member_technical_problem_tenant_fk;
alter table retrieval.packet_member drop constraint packet_member_solution_pattern_tenant_fk;
alter table retrieval.packet_member drop constraint packet_member_advanced_usage_pattern_tenant_fk;
alter table retrieval.packet_member drop constraint packet_member_implementation_example_tenant_fk;
alter table retrieval.packet_member drop constraint packet_member_failure_mode_tenant_fk;
alter table retrieval.packet_member drop constraint packet_member_benchmark_result_tenant_fk;
alter table retrieval.packet_member drop constraint packet_member_compatibility_constraint_tenant_fk;
alter table retrieval.packet_member drop constraint packet_member_operational_practice_tenant_fk;
alter table retrieval.packet_member drop constraint packet_member_security_consideration_tenant_fk;
alter table retrieval.chunk_citation_link drop constraint chunk_citation_link_tenant_id_chunk_id_fkey;
alter table corpus.organization drop constraint organization_merged_into_id_fkey;
alter table corpus.organization drop constraint organization_created_by_receipt_id_fkey;
alter table corpus.organization drop constraint organization_updated_by_receipt_id_fkey;
alter table corpus.organization_identifier drop constraint organization_identifier_organization_id_fkey;
alter table corpus.organization_identifier drop constraint organization_identifier_created_by_receipt_id_fkey;
alter table corpus.person drop constraint person_primary_organization_id_fkey;
alter table corpus.person drop constraint person_merged_into_id_fkey;
alter table corpus.person drop constraint person_created_by_receipt_id_fkey;
alter table corpus.person drop constraint person_updated_by_receipt_id_fkey;
alter table corpus.person_identifier drop constraint person_identifier_person_id_fkey;
alter table corpus.person_identifier drop constraint person_identifier_created_by_receipt_id_fkey;
alter table corpus.repository drop constraint repository_merged_into_id_fkey;
alter table corpus.repository drop constraint repository_created_by_receipt_id_fkey;
alter table corpus.repository drop constraint repository_updated_by_receipt_id_fkey;
alter table corpus.repository_alias drop constraint repository_alias_repository_id_fkey;
alter table corpus.repository_alias drop constraint repository_alias_created_by_receipt_id_fkey;
alter table corpus.library drop constraint library_ecosystem_fkey;
alter table corpus.library drop constraint library_merged_into_id_fkey;
alter table corpus.library drop constraint library_created_by_receipt_id_fkey;
alter table corpus.library drop constraint library_updated_by_receipt_id_fkey;
alter table corpus.paper drop constraint paper_merged_into_id_fkey;
alter table corpus.paper drop constraint paper_created_by_receipt_id_fkey;
alter table corpus.paper drop constraint paper_updated_by_receipt_id_fkey;
alter table corpus.benchmark drop constraint benchmark_merged_into_id_fkey;
alter table corpus.benchmark drop constraint benchmark_created_by_receipt_id_fkey;
alter table corpus.benchmark drop constraint benchmark_updated_by_receipt_id_fkey;
alter table corpus.ai_protocol_version drop constraint ai_protocol_version_ai_protocol_id_fkey;
alter table corpus.ai_protocol_version drop constraint ai_protocol_version_created_by_receipt_id_fkey;
alter table corpus.video drop constraint video_transcript_artifact_id_fkey;
alter table corpus.video drop constraint video_merged_into_id_fkey;
alter table corpus.video drop constraint video_created_by_receipt_id_fkey;
alter table corpus.video drop constraint video_updated_by_receipt_id_fkey;
alter table corpus.talk drop constraint talk_recording_video_id_fkey;
alter table corpus.talk drop constraint talk_merged_into_id_fkey;
alter table corpus.talk drop constraint talk_created_by_receipt_id_fkey;
alter table corpus.talk drop constraint talk_updated_by_receipt_id_fkey;
alter table corpus.product drop constraint product_vendor_organization_id_fkey;
alter table corpus.product drop constraint product_merged_into_id_fkey;
alter table corpus.product drop constraint product_created_by_receipt_id_fkey;
alter table corpus.product drop constraint product_updated_by_receipt_id_fkey;
alter table corpus.ai_protocol drop constraint ai_protocol_spec_repository_id_fkey;
alter table corpus.ai_protocol drop constraint ai_protocol_merged_into_id_fkey;
alter table corpus.ai_protocol drop constraint ai_protocol_created_by_receipt_id_fkey;
alter table corpus.ai_protocol drop constraint ai_protocol_updated_by_receipt_id_fkey;
alter table corpus.concept drop constraint concept_merged_into_id_fkey;
alter table corpus.concept drop constraint concept_created_by_receipt_id_fkey;
alter table corpus.concept drop constraint concept_updated_by_receipt_id_fkey;
alter table corpus.concept_alias drop constraint concept_alias_concept_id_fkey;
alter table corpus.concept_alias drop constraint concept_alias_created_by_receipt_id_fkey;
alter table corpus.dataset drop constraint dataset_merged_into_id_fkey;
alter table corpus.dataset drop constraint dataset_created_by_receipt_id_fkey;
alter table corpus.dataset drop constraint dataset_updated_by_receipt_id_fkey;
alter table corpus.ai_model drop constraint ai_model_provider_organization_id_fkey;
alter table corpus.ai_model drop constraint ai_model_merged_into_id_fkey;
alter table corpus.ai_model drop constraint ai_model_created_by_receipt_id_fkey;
alter table corpus.ai_model drop constraint ai_model_updated_by_receipt_id_fkey;
alter table corpus.ai_model_version drop constraint ai_model_version_ai_model_id_fkey;
alter table corpus.ai_model_version drop constraint ai_model_version_created_by_receipt_id_fkey;
alter table corpus.ai_protocol drop constraint ai_protocol_governing_organization_id_fkey;
alter table corpus.mcp_server drop constraint mcp_server_ecosystem_fkey;
alter table corpus.mcp_server drop constraint mcp_server_repository_id_fkey;
alter table corpus.mcp_server drop constraint mcp_server_maintainer_organization_id_fkey;
alter table corpus.mcp_server drop constraint mcp_server_distribution_kind_fkey;
alter table corpus.mcp_server drop constraint mcp_server_merged_into_id_fkey;
alter table corpus.mcp_server drop constraint mcp_server_created_by_receipt_id_fkey;
alter table corpus.mcp_server drop constraint mcp_server_updated_by_receipt_id_fkey;
alter table corpus.mcp_server_version drop constraint mcp_server_version_mcp_server_id_fkey;
alter table corpus.mcp_server_version drop constraint mcp_server_version_protocol_version_id_fkey;
alter table corpus.mcp_server_version drop constraint mcp_server_version_created_by_receipt_id_fkey;
alter table corpus.mcp_server_tool drop constraint mcp_server_tool_mcp_server_version_id_fkey;
alter table corpus.mcp_server_tool drop constraint mcp_server_tool_created_by_receipt_id_fkey;
alter table corpus.mcp_server_resource drop constraint mcp_server_resource_mcp_server_version_id_fkey;
alter table corpus.mcp_server_resource drop constraint mcp_server_resource_created_by_receipt_id_fkey;
alter table corpus.mcp_server_prompt drop constraint mcp_server_prompt_mcp_server_version_id_fkey;
alter table corpus.mcp_server_prompt drop constraint mcp_server_prompt_created_by_receipt_id_fkey;
alter table corpus.repository_archival_fact drop constraint repository_archival_fact_repository_id_fkey;
alter table corpus.repository_archival_fact drop constraint repository_archival_fact_provenance_claim_id_fkey;
alter table corpus.repository_archival_fact drop constraint repository_archival_fact_created_by_receipt_id_fkey;
alter table corpus.agent_skill drop constraint agent_skill_repository_id_fkey;
alter table corpus.agent_skill drop constraint agent_skill_maintainer_organization_id_fkey;
alter table corpus.agent_skill drop constraint agent_skill_merged_into_id_fkey;
alter table corpus.agent_skill drop constraint agent_skill_created_by_receipt_id_fkey;
alter table corpus.agent_skill drop constraint agent_skill_updated_by_receipt_id_fkey;
alter table corpus.agent_skill_version drop constraint agent_skill_version_agent_skill_id_fkey;
alter table corpus.agent_skill_version drop constraint agent_skill_version_created_by_receipt_id_fkey;
alter table corpus.library_license_fact drop constraint library_license_fact_library_id_fkey;
alter table corpus.library_license_fact drop constraint library_license_fact_provenance_claim_id_fkey;
alter table corpus.library_license_fact drop constraint library_license_fact_created_by_receipt_id_fkey;
alter table corpus.library_maintenance_status_fact drop constraint library_maintenance_status_fact_library_id_fkey;
alter table corpus.library_maintenance_status_fact drop constraint library_maintenance_status_fact_provenance_claim_id_fkey;
alter table corpus.library_maintenance_status_fact drop constraint library_maintenance_status_fact_created_by_receipt_id_fkey;
alter table corpus.ai_model_availability_fact drop constraint ai_model_availability_fact_ai_model_version_id_fkey;
alter table corpus.ai_model_availability_fact drop constraint ai_model_availability_fact_provenance_claim_id_fkey;
alter table corpus.ai_model_availability_fact drop constraint ai_model_availability_fact_created_by_receipt_id_fkey;
alter table corpus.mcp_server_registry_status_fact drop constraint mcp_server_registry_status_fact_mcp_server_id_fkey;
alter table corpus.mcp_server_registry_status_fact drop constraint mcp_server_registry_status_fact_provenance_claim_id_fkey;
alter table corpus.mcp_server_registry_status_fact drop constraint mcp_server_registry_status_fact_created_by_receipt_id_fkey;
alter table corpus.paper_retraction_fact drop constraint paper_retraction_fact_paper_id_fkey;
alter table corpus.paper_retraction_fact drop constraint paper_retraction_fact_provenance_claim_id_fkey;
alter table corpus.paper_retraction_fact drop constraint paper_retraction_fact_created_by_receipt_id_fkey;
alter table corpus.library_maintained_by_person drop constraint library_maintained_by_person_library_id_fkey;
alter table corpus.library_maintained_by_person drop constraint library_maintained_by_person_person_id_fkey;
alter table corpus.library_maintained_by_person drop constraint library_maintained_by_person_provenance_claim_id_fkey;
alter table corpus.library_maintained_by_person drop constraint library_maintained_by_person_created_by_receipt_id_fkey;
alter table corpus.paper_authored_by_person drop constraint paper_authored_by_person_paper_id_fkey;
alter table corpus.paper_authored_by_person drop constraint paper_authored_by_person_person_id_fkey;
alter table corpus.paper_authored_by_person drop constraint paper_authored_by_person_affiliation_organization_id_fkey;
alter table corpus.paper_authored_by_person drop constraint paper_authored_by_person_provenance_claim_id_fkey;
alter table corpus.paper_authored_by_person drop constraint paper_authored_by_person_created_by_receipt_id_fkey;
alter table corpus.repository_implements_paper drop constraint repository_implements_paper_repository_id_fkey;
alter table corpus.repository_implements_paper drop constraint repository_implements_paper_paper_id_fkey;
alter table corpus.repository_implements_paper drop constraint repository_implements_paper_provenance_claim_id_fkey;
alter table corpus.repository_implements_paper drop constraint repository_implements_paper_created_by_receipt_id_fkey;
alter table corpus.talk_explains_concept drop constraint talk_explains_concept_talk_id_fkey;
alter table corpus.talk_explains_concept drop constraint talk_explains_concept_concept_id_fkey;
alter table corpus.talk_explains_concept drop constraint talk_explains_concept_provenance_claim_id_fkey;
alter table corpus.library_depends_on_library drop constraint library_depends_on_library_library_id_fkey;
alter table corpus.library_depends_on_library drop constraint library_depends_on_library_depends_on_id_fkey;
alter table corpus.library_depends_on_library drop constraint library_depends_on_library_provenance_claim_id_fkey;
alter table corpus.library_depends_on_library drop constraint library_depends_on_library_created_by_receipt_id_fkey;
alter table corpus.person_employed_by_organization drop constraint person_employed_by_organization_person_id_fkey;
alter table corpus.person_employed_by_organization drop constraint person_employed_by_organization_organization_id_fkey;
alter table corpus.person_employed_by_organization drop constraint person_employed_by_organization_provenance_claim_id_fkey;
alter table corpus.person_employed_by_organization drop constraint person_employed_by_organization_created_by_receipt_id_fkey;
alter table corpus.person_founded_organization drop constraint person_founded_organization_person_id_fkey;
alter table corpus.person_founded_organization drop constraint person_founded_organization_organization_id_fkey;
alter table corpus.person_founded_organization drop constraint person_founded_organization_provenance_claim_id_fkey;
alter table corpus.person_founded_organization drop constraint person_founded_organization_created_by_receipt_id_fkey;
alter table corpus.talk_explains_concept drop constraint talk_explains_concept_created_by_receipt_id_fkey;
alter table corpus.person_presented_at_talk drop constraint person_presented_at_talk_person_id_fkey;
alter table corpus.person_presented_at_talk drop constraint person_presented_at_talk_talk_id_fkey;
alter table corpus.person_presented_at_talk drop constraint person_presented_at_talk_provenance_claim_id_fkey;
alter table corpus.person_presented_at_talk drop constraint person_presented_at_talk_created_by_receipt_id_fkey;
alter table corpus.library_backed_by_repository drop constraint library_backed_by_repository_library_id_fkey;
alter table corpus.library_backed_by_repository drop constraint library_backed_by_repository_repository_id_fkey;
alter table corpus.library_backed_by_repository drop constraint library_backed_by_repository_provenance_claim_id_fkey;
alter table corpus.library_backed_by_repository drop constraint library_backed_by_repository_created_by_receipt_id_fkey;
alter table corpus.library_appeared_in_video drop constraint library_appeared_in_video_library_id_fkey;
alter table corpus.library_appeared_in_video drop constraint library_appeared_in_video_video_id_fkey;
alter table corpus.library_appeared_in_video drop constraint library_appeared_in_video_locator_id_fkey;
alter table corpus.library_appeared_in_video drop constraint library_appeared_in_video_provenance_claim_id_fkey;
alter table corpus.library_appeared_in_video drop constraint library_appeared_in_video_created_by_receipt_id_fkey;
alter table corpus.person_appeared_in_video drop constraint person_appeared_in_video_person_id_fkey;
alter table corpus.person_appeared_in_video drop constraint person_appeared_in_video_video_id_fkey;
alter table corpus.person_appeared_in_video drop constraint person_appeared_in_video_locator_id_fkey;
alter table corpus.person_appeared_in_video drop constraint person_appeared_in_video_provenance_claim_id_fkey;
alter table corpus.person_appeared_in_video drop constraint person_appeared_in_video_created_by_receipt_id_fkey;
alter table corpus.paper_appeared_in_video drop constraint paper_appeared_in_video_paper_id_fkey;
alter table corpus.paper_appeared_in_video drop constraint paper_appeared_in_video_video_id_fkey;
alter table corpus.paper_appeared_in_video drop constraint paper_appeared_in_video_locator_id_fkey;
alter table corpus.paper_appeared_in_video drop constraint paper_appeared_in_video_provenance_claim_id_fkey;
alter table corpus.paper_appeared_in_video drop constraint paper_appeared_in_video_created_by_receipt_id_fkey;
alter table corpus.product_appeared_in_video drop constraint product_appeared_in_video_product_id_fkey;
alter table corpus.product_appeared_in_video drop constraint product_appeared_in_video_video_id_fkey;
alter table corpus.product_appeared_in_video drop constraint product_appeared_in_video_locator_id_fkey;
alter table corpus.product_appeared_in_video drop constraint product_appeared_in_video_provenance_claim_id_fkey;
alter table corpus.product_appeared_in_video drop constraint product_appeared_in_video_created_by_receipt_id_fkey;
alter table corpus.paper_appeared_in_talk drop constraint paper_appeared_in_talk_paper_id_fkey;
alter table corpus.paper_appeared_in_talk drop constraint paper_appeared_in_talk_talk_id_fkey;
alter table corpus.paper_appeared_in_talk drop constraint paper_appeared_in_talk_provenance_claim_id_fkey;
alter table corpus.paper_appeared_in_talk drop constraint paper_appeared_in_talk_created_by_receipt_id_fkey;
alter table corpus.mcp_server_backed_by_repository drop constraint mcp_server_backed_by_repository_mcp_server_id_fkey;
alter table corpus.mcp_server_backed_by_repository drop constraint mcp_server_backed_by_repository_repository_id_fkey;
alter table corpus.mcp_server_backed_by_repository drop constraint mcp_server_backed_by_repository_provenance_claim_id_fkey;
alter table corpus.mcp_server_backed_by_repository drop constraint mcp_server_backed_by_repository_created_by_receipt_id_fkey;
alter table corpus.mcp_server_wraps_product drop constraint mcp_server_wraps_product_mcp_server_id_fkey;
alter table corpus.mcp_server_wraps_product drop constraint mcp_server_wraps_product_product_id_fkey;
alter table corpus.mcp_server_wraps_product drop constraint mcp_server_wraps_product_provenance_claim_id_fkey;
alter table corpus.mcp_server_wraps_product drop constraint mcp_server_wraps_product_created_by_receipt_id_fkey;
alter table corpus.library_implements_protocol_version drop constraint library_implements_protocol_version_library_id_fkey;
alter table corpus.library_implements_protocol_version drop constraint library_implements_protocol_version_ai_protocol_version_id_fkey;
alter table corpus.library_implements_protocol_version drop constraint library_implements_protocol_version_provenance_claim_id_fkey;
alter table corpus.library_implements_protocol_version drop constraint library_implements_protocol_version_created_by_receipt_id_fkey;
alter table corpus.product_implements_protocol_version drop constraint product_implements_protocol_version_product_id_fkey;
alter table corpus.product_implements_protocol_version drop constraint product_implements_protocol_version_ai_protocol_version_id_fkey;
alter table corpus.product_implements_protocol_version drop constraint product_implements_protocol_version_provenance_claim_id_fkey;
alter table corpus.product_implements_protocol_version drop constraint product_implements_protocol_version_created_by_receipt_id_fkey;
alter table corpus.agent_skill_requires_mcp_server drop constraint agent_skill_requires_mcp_server_agent_skill_id_fkey;
alter table corpus.agent_skill_requires_mcp_server drop constraint agent_skill_requires_mcp_server_mcp_server_id_fkey;
alter table corpus.agent_skill_requires_mcp_server drop constraint agent_skill_requires_mcp_server_provenance_claim_id_fkey;
alter table corpus.agent_skill_requires_mcp_server drop constraint agent_skill_requires_mcp_server_created_by_receipt_id_fkey;
alter table corpus.agent_skill_targets_library drop constraint agent_skill_targets_library_agent_skill_id_fkey;
alter table corpus.agent_skill_targets_library drop constraint agent_skill_targets_library_library_id_fkey;
alter table corpus.agent_skill_targets_library drop constraint agent_skill_targets_library_provenance_claim_id_fkey;
alter table corpus.agent_skill_targets_library drop constraint agent_skill_targets_library_created_by_receipt_id_fkey;
alter table corpus.ai_model_released_by_organization drop constraint ai_model_released_by_organization_ai_model_id_fkey;
alter table corpus.ai_model_released_by_organization drop constraint ai_model_released_by_organization_organization_id_fkey;
alter table corpus.ai_model_released_by_organization drop constraint ai_model_released_by_organization_provenance_claim_id_fkey;
alter table corpus.ai_model_released_by_organization drop constraint ai_model_released_by_organization_created_by_receipt_id_fkey;
alter table corpus.product_built_on_model_version drop constraint product_built_on_model_version_product_id_fkey;
alter table corpus.product_built_on_model_version drop constraint product_built_on_model_version_ai_model_version_id_fkey;
alter table corpus.product_built_on_model_version drop constraint product_built_on_model_version_provenance_claim_id_fkey;
alter table corpus.product_built_on_model_version drop constraint product_built_on_model_version_created_by_receipt_id_fkey;
alter table corpus.library_supports_model_version drop constraint library_supports_model_version_library_id_fkey;
alter table corpus.library_supports_model_version drop constraint library_supports_model_version_ai_model_version_id_fkey;
alter table corpus.library_supports_model_version drop constraint library_supports_model_version_provenance_claim_id_fkey;
alter table corpus.library_supports_model_version drop constraint library_supports_model_version_created_by_receipt_id_fkey;
alter table corpus.person_created_mcp_server drop constraint person_created_mcp_server_person_id_fkey;
alter table corpus.person_created_mcp_server drop constraint person_created_mcp_server_mcp_server_id_fkey;
alter table corpus.person_created_mcp_server drop constraint person_created_mcp_server_provenance_claim_id_fkey;
alter table corpus.person_created_mcp_server drop constraint person_created_mcp_server_created_by_receipt_id_fkey;
alter table corpus.person_created_agent_skill drop constraint person_created_agent_skill_person_id_fkey;
alter table corpus.person_created_agent_skill drop constraint person_created_agent_skill_agent_skill_id_fkey;
alter table corpus.person_created_agent_skill drop constraint person_created_agent_skill_provenance_claim_id_fkey;
alter table corpus.person_created_agent_skill drop constraint person_created_agent_skill_created_by_receipt_id_fkey;
alter table corpus.entity_merge drop constraint entity_merge_created_by_receipt_id_fkey;
alter table knowledge.technical_problem drop constraint technical_problem_assurance_level_fkey;
alter table knowledge.technical_problem drop constraint technical_problem_revalidation_policy_id_fkey;
alter table knowledge.technical_problem drop constraint technical_problem_provenance_claim_id_fkey;
alter table knowledge.technical_problem drop constraint technical_problem_superseded_by_id_fkey;
alter table knowledge.technical_problem drop constraint technical_problem_created_by_receipt_id_fkey;
alter table knowledge.technical_problem drop constraint technical_problem_updated_by_receipt_id_fkey;
alter table knowledge.solution_pattern drop constraint solution_pattern_assurance_level_fkey;
alter table knowledge.solution_pattern drop constraint solution_pattern_revalidation_policy_id_fkey;
alter table knowledge.solution_pattern drop constraint solution_pattern_provenance_claim_id_fkey;
alter table knowledge.solution_pattern drop constraint solution_pattern_superseded_by_id_fkey;
alter table knowledge.solution_pattern drop constraint solution_pattern_created_by_receipt_id_fkey;
alter table knowledge.solution_pattern drop constraint solution_pattern_updated_by_receipt_id_fkey;
alter table knowledge.advanced_usage_pattern drop constraint advanced_usage_pattern_assurance_level_fkey;
alter table knowledge.advanced_usage_pattern drop constraint advanced_usage_pattern_revalidation_policy_id_fkey;
alter table knowledge.advanced_usage_pattern drop constraint advanced_usage_pattern_provenance_claim_id_fkey;
alter table knowledge.advanced_usage_pattern drop constraint advanced_usage_pattern_superseded_by_id_fkey;
alter table knowledge.advanced_usage_pattern drop constraint advanced_usage_pattern_created_by_receipt_id_fkey;
alter table knowledge.advanced_usage_pattern drop constraint advanced_usage_pattern_updated_by_receipt_id_fkey;
alter table knowledge.advanced_usage_pattern drop constraint advanced_usage_pattern_library_id_fkey;
alter table knowledge.advanced_usage_pattern drop constraint advanced_usage_pattern_minimal_example_artifact_id_fkey;
alter table knowledge.implementation_example drop constraint implementation_example_assurance_level_fkey;
alter table knowledge.implementation_example drop constraint implementation_example_revalidation_policy_id_fkey;
alter table knowledge.implementation_example drop constraint implementation_example_provenance_claim_id_fkey;
alter table knowledge.implementation_example drop constraint implementation_example_superseded_by_id_fkey;
alter table knowledge.implementation_example drop constraint implementation_example_created_by_receipt_id_fkey;
alter table knowledge.implementation_example drop constraint implementation_example_updated_by_receipt_id_fkey;
alter table knowledge.implementation_example drop constraint implementation_example_repository_id_fkey;
alter table knowledge.implementation_example drop constraint implementation_example_exec_verification_id_fkey;
alter table knowledge.failure_mode drop constraint failure_mode_assurance_level_fkey;
alter table knowledge.failure_mode drop constraint failure_mode_revalidation_policy_id_fkey;
alter table knowledge.failure_mode drop constraint failure_mode_provenance_claim_id_fkey;
alter table knowledge.failure_mode drop constraint failure_mode_superseded_by_id_fkey;
alter table knowledge.failure_mode drop constraint failure_mode_created_by_receipt_id_fkey;
alter table knowledge.failure_mode drop constraint failure_mode_updated_by_receipt_id_fkey;
alter table knowledge.benchmark_result drop constraint benchmark_result_assurance_level_fkey;
alter table knowledge.benchmark_result drop constraint benchmark_result_revalidation_policy_id_fkey;
alter table knowledge.benchmark_result drop constraint benchmark_result_provenance_claim_id_fkey;
alter table knowledge.benchmark_result drop constraint benchmark_result_superseded_by_id_fkey;
alter table knowledge.benchmark_result drop constraint benchmark_result_created_by_receipt_id_fkey;
alter table knowledge.benchmark_result drop constraint benchmark_result_updated_by_receipt_id_fkey;
alter table knowledge.benchmark_result drop constraint benchmark_result_benchmark_id_fkey;
alter table knowledge.compatibility_constraint drop constraint compatibility_constraint_assurance_level_fkey;
alter table knowledge.compatibility_constraint drop constraint compatibility_constraint_revalidation_policy_id_fkey;
alter table knowledge.compatibility_constraint drop constraint compatibility_constraint_provenance_claim_id_fkey;
alter table knowledge.compatibility_constraint drop constraint compatibility_constraint_superseded_by_id_fkey;
alter table knowledge.compatibility_constraint drop constraint compatibility_constraint_created_by_receipt_id_fkey;
alter table knowledge.compatibility_constraint drop constraint compatibility_constraint_updated_by_receipt_id_fkey;
alter table knowledge.operational_practice drop constraint operational_practice_assurance_level_fkey;
alter table knowledge.operational_practice drop constraint operational_practice_revalidation_policy_id_fkey;
alter table knowledge.operational_practice drop constraint operational_practice_provenance_claim_id_fkey;
alter table knowledge.operational_practice drop constraint operational_practice_superseded_by_id_fkey;
alter table knowledge.operational_practice drop constraint operational_practice_created_by_receipt_id_fkey;
alter table knowledge.operational_practice drop constraint operational_practice_updated_by_receipt_id_fkey;
alter table knowledge.security_consideration drop constraint security_consideration_assurance_level_fkey;
alter table knowledge.security_consideration drop constraint security_consideration_revalidation_policy_id_fkey;
alter table knowledge.security_consideration drop constraint security_consideration_provenance_claim_id_fkey;
alter table knowledge.security_consideration drop constraint security_consideration_superseded_by_id_fkey;
alter table knowledge.security_consideration drop constraint security_consideration_created_by_receipt_id_fkey;
alter table knowledge.security_consideration drop constraint security_consideration_updated_by_receipt_id_fkey;
alter table knowledge.library_addresses_problem drop constraint library_addresses_problem_library_id_fkey;
alter table knowledge.library_addresses_problem drop constraint library_addresses_problem_technical_problem_id_fkey;
alter table knowledge.library_addresses_problem drop constraint library_addresses_problem_provenance_claim_id_fkey;
alter table knowledge.library_addresses_problem drop constraint library_addresses_problem_created_by_receipt_id_fkey;
alter table knowledge.problem_solved_by_solution drop constraint problem_solved_by_solution_technical_problem_id_fkey;
alter table knowledge.problem_solved_by_solution drop constraint problem_solved_by_solution_solution_pattern_id_fkey;
alter table knowledge.problem_solved_by_solution drop constraint problem_solved_by_solution_provenance_claim_id_fkey;
alter table knowledge.problem_solved_by_solution drop constraint problem_solved_by_solution_created_by_receipt_id_fkey;
alter table knowledge.solution_applies_under_constraint drop constraint solution_applies_under_constraint_solution_pattern_id_fkey;
alter table knowledge.solution_applies_under_constraint drop constraint solution_applies_under_constra_compatibility_constraint_id_fkey;
alter table knowledge.solution_applies_under_constraint drop constraint solution_applies_under_constraint_provenance_claim_id_fkey;
alter table knowledge.solution_applies_under_constraint drop constraint solution_applies_under_constraint_created_by_receipt_id_fkey;
alter table knowledge.implementation_demonstrates_pattern drop constraint implementation_demonstrates_patt_implementation_example_id_fkey;
alter table knowledge.implementation_demonstrates_pattern drop constraint implementation_demonstrates_pattern_solution_pattern_id_fkey;
alter table knowledge.implementation_demonstrates_pattern drop constraint implementation_demonstrates_patt_advanced_usage_pattern_id_fkey;
alter table knowledge.implementation_demonstrates_pattern drop constraint implementation_demonstrates_pattern_provenance_claim_id_fkey;
alter table knowledge.implementation_demonstrates_pattern drop constraint implementation_demonstrates_pattern_created_by_receipt_id_fkey;
alter table knowledge.repository_contains_implementation drop constraint repository_contains_implementation_repository_id_fkey;
alter table knowledge.repository_contains_implementation drop constraint repository_contains_implementati_implementation_example_id_fkey;
alter table knowledge.repository_contains_implementation drop constraint repository_contains_implementation_provenance_claim_id_fkey;
alter table knowledge.repository_contains_implementation drop constraint repository_contains_implementation_created_by_receipt_id_fkey;
alter table knowledge.paper_supports_solution drop constraint paper_supports_solution_paper_id_fkey;
alter table knowledge.paper_supports_solution drop constraint paper_supports_solution_solution_pattern_id_fkey;
alter table knowledge.paper_supports_solution drop constraint paper_supports_solution_provenance_claim_id_fkey;
alter table knowledge.paper_supports_solution drop constraint paper_supports_solution_created_by_receipt_id_fkey;
alter table knowledge.failure_mode_affects_library_version drop constraint failure_mode_affects_library_version_failure_mode_id_fkey;
alter table knowledge.failure_mode_affects_library_version drop constraint failure_mode_affects_library_version_library_id_fkey;
alter table knowledge.failure_mode_affects_library_version drop constraint failure_mode_affects_library_version_provenance_claim_id_fkey;
alter table knowledge.failure_mode_affects_library_version drop constraint failure_mode_affects_library_version_created_by_receipt_id_fkey;
alter table knowledge.failure_mode_affects_mcp_server drop constraint failure_mode_affects_mcp_server_failure_mode_id_fkey;
alter table knowledge.failure_mode_affects_mcp_server drop constraint failure_mode_affects_mcp_server_mcp_server_id_fkey;
alter table knowledge.failure_mode_affects_mcp_server drop constraint failure_mode_affects_mcp_server_provenance_claim_id_fkey;
alter table knowledge.failure_mode_affects_mcp_server drop constraint failure_mode_affects_mcp_server_created_by_receipt_id_fkey;
alter table knowledge.benchmark_compares_libraries drop constraint benchmark_compares_libraries_benchmark_result_id_fkey;
alter table knowledge.benchmark_compares_libraries drop constraint benchmark_compares_libraries_library_id_fkey;
alter table knowledge.benchmark_compares_libraries drop constraint benchmark_compares_libraries_provenance_claim_id_fkey;
alter table knowledge.benchmark_compares_libraries drop constraint benchmark_compares_libraries_created_by_receipt_id_fkey;
alter table knowledge.talk_explains_pattern drop constraint talk_explains_pattern_talk_id_fkey;
alter table knowledge.talk_explains_pattern drop constraint talk_explains_pattern_solution_pattern_id_fkey;
alter table knowledge.talk_explains_pattern drop constraint talk_explains_pattern_advanced_usage_pattern_id_fkey;
alter table knowledge.talk_explains_pattern drop constraint talk_explains_pattern_provenance_claim_id_fkey;
alter table knowledge.talk_explains_pattern drop constraint talk_explains_pattern_created_by_receipt_id_fkey;
alter table knowledge.solution_uses_protocol_version drop constraint solution_uses_protocol_version_solution_pattern_id_fkey;
alter table knowledge.solution_uses_protocol_version drop constraint solution_uses_protocol_version_ai_protocol_version_id_fkey;
alter table knowledge.solution_uses_protocol_version drop constraint solution_uses_protocol_version_provenance_claim_id_fkey;
alter table knowledge.solution_uses_protocol_version drop constraint solution_uses_protocol_version_created_by_receipt_id_fkey;
alter table staging.candidate drop constraint candidate_discovered_by_attempt_id_fkey;
alter table staging.candidate drop constraint candidate_capture_id_fkey;
alter table staging.candidate drop constraint candidate_locator_id_fkey;
alter table staging.candidate drop constraint candidate_mission_id_fkey;
alter table staging.candidate_library drop constraint candidate_library_candidate_id_fkey;
alter table staging.candidate_library drop constraint candidate_library_candidate_id_candidate_kind_fkey;
alter table staging.candidate_repository drop constraint candidate_repository_candidate_id_fkey;
alter table staging.candidate_repository drop constraint candidate_repository_candidate_id_candidate_kind_fkey;
alter table staging.candidate_person drop constraint candidate_person_candidate_id_fkey;
alter table staging.candidate_person drop constraint candidate_person_candidate_id_candidate_kind_fkey;
alter table staging.candidate_organization drop constraint candidate_organization_candidate_id_fkey;
alter table staging.candidate_organization drop constraint candidate_organization_candidate_id_candidate_kind_fkey;
alter table staging.candidate_technical_record drop constraint candidate_technical_record_candidate_id_fkey;
alter table staging.candidate_paper drop constraint candidate_paper_candidate_id_fkey;
alter table staging.candidate_paper drop constraint candidate_paper_candidate_id_candidate_kind_fkey;
alter table staging.candidate_video drop constraint candidate_video_candidate_id_fkey;
alter table staging.candidate_video drop constraint candidate_video_candidate_id_candidate_kind_fkey;
alter table staging.candidate_talk drop constraint candidate_talk_candidate_id_fkey;
alter table staging.candidate_talk drop constraint candidate_talk_candidate_id_candidate_kind_fkey;
alter table staging.candidate_product drop constraint candidate_product_candidate_id_fkey;
alter table staging.candidate_product drop constraint candidate_product_candidate_id_candidate_kind_fkey;
alter table staging.candidate_concept drop constraint candidate_concept_candidate_id_fkey;
alter table staging.candidate_concept drop constraint candidate_concept_candidate_id_candidate_kind_fkey;
alter table staging.candidate_dataset drop constraint candidate_dataset_candidate_id_fkey;
alter table staging.candidate_dataset drop constraint candidate_dataset_candidate_id_candidate_kind_fkey;
alter table staging.candidate_technical_record drop constraint candidate_technical_record_candidate_id_candidate_kind_fkey;
alter table staging.candidate_benchmark drop constraint candidate_benchmark_candidate_id_fkey;
alter table staging.candidate_benchmark drop constraint candidate_benchmark_candidate_id_candidate_kind_fkey;
alter table staging.candidate_ai_model drop constraint candidate_ai_model_candidate_id_fkey;
alter table staging.candidate_ai_model drop constraint candidate_ai_model_candidate_id_candidate_kind_fkey;
alter table staging.candidate_ai_protocol drop constraint candidate_ai_protocol_candidate_id_fkey;
alter table staging.candidate_ai_protocol drop constraint candidate_ai_protocol_candidate_id_candidate_kind_fkey;
alter table staging.candidate_mcp_server drop constraint candidate_mcp_server_candidate_id_fkey;
alter table staging.candidate_mcp_server drop constraint candidate_mcp_server_candidate_id_candidate_kind_fkey;
alter table staging.candidate_agent_skill drop constraint candidate_agent_skill_candidate_id_fkey;
alter table staging.candidate_agent_skill drop constraint candidate_agent_skill_candidate_id_candidate_kind_fkey;
alter table staging.mention drop constraint mention_candidate_id_fkey;
alter table staging.mention drop constraint mention_appeared_in_capture_id_fkey;
alter table staging.mention drop constraint mention_snippet_locator_id_fkey;
alter table staging.identity_match drop constraint identity_match_candidate_id_fkey;
alter table staging.identity_match drop constraint identity_match_organization_id_fkey;
alter table staging.identity_match drop constraint identity_match_person_id_fkey;
alter table staging.identity_match drop constraint identity_match_library_id_fkey;
alter table staging.identity_match drop constraint identity_match_repository_id_fkey;
alter table staging.identity_match drop constraint identity_match_paper_id_fkey;
alter table staging.identity_match drop constraint identity_match_talk_id_fkey;
alter table staging.identity_match drop constraint identity_match_video_id_fkey;
alter table staging.identity_match drop constraint identity_match_product_id_fkey;
alter table staging.identity_match drop constraint identity_match_concept_id_fkey;
alter table staging.identity_match drop constraint identity_match_dataset_id_fkey;
alter table staging.identity_match drop constraint identity_match_benchmark_id_fkey;
alter table staging.identity_match drop constraint identity_match_ai_model_id_fkey;
alter table staging.identity_match drop constraint identity_match_ai_protocol_id_fkey;
alter table staging.identity_match drop constraint identity_match_mcp_server_id_fkey;
alter table staging.identity_match drop constraint identity_match_agent_skill_id_fkey;
alter table ranking.metric_observation drop constraint metric_observation_repository_id_fkey;
alter table ranking.metric_observation drop constraint metric_observation_person_id_fkey;
alter table ranking.metric_observation drop constraint metric_observation_organization_id_fkey;
alter table ranking.metric_observation drop constraint metric_observation_paper_id_fkey;
alter table staging.resolution_decision drop constraint resolution_decision_candidate_id_fkey;
alter table staging.resolution_decision drop constraint resolution_decision_identity_match_id_fkey;
alter table staging.resolution_decision drop constraint resolution_decision_intent_id_fkey;
alter table staging.resolution_decision drop constraint resolution_decision_decided_by_attempt_id_fkey;
alter table staging.vetting_decision drop constraint vetting_decision_candidate_id_fkey;
alter table staging.vetting_decision drop constraint vetting_decision_decided_by_attempt_id_fkey;
alter table ranking.metric_definition_version drop constraint metric_definition_version_metric_definition_id_fkey;
alter table ranking.metric_observation drop constraint metric_observation_definition_version_id_fkey;
alter table ranking.metric_observation drop constraint metric_observation_library_id_fkey;
alter table ranking.metric_observation drop constraint metric_observation_video_id_fkey;
alter table ranking.metric_observation drop constraint metric_observation_ai_model_version_id_fkey;
alter table ranking.metric_observation drop constraint metric_observation_mcp_server_id_fkey;
alter table ranking.metric_observation drop constraint metric_observation_agent_skill_id_fkey;
alter table ranking.metric_observation drop constraint metric_observation_product_id_fkey;
alter table ranking.metric_observation drop constraint metric_observation_locator_id_fkey;
alter table ranking.feature_value drop constraint feature_value_feature_definition_id_fkey;
alter table ranking.ranking_result drop constraint ranking_result_run_id_fkey;
alter table staging.vetting_decision drop constraint vetting_decision_review_task_fk;
alter table ranking.metric_observation drop constraint metric_observation_run_fk;
alter table evidence.claim_library drop constraint claim_library_claim_id_fkey;
alter table evidence.claim_library drop constraint claim_library_library_id_fkey;
alter table evidence.claim_repository drop constraint claim_repository_claim_id_fkey;
alter table evidence.claim_repository drop constraint claim_repository_repository_id_fkey;
alter table evidence.claim_person drop constraint claim_person_claim_id_fkey;
alter table evidence.claim_person drop constraint claim_person_person_id_fkey;
alter table evidence.claim_organization drop constraint claim_organization_claim_id_fkey;
alter table evidence.claim_organization drop constraint claim_organization_organization_id_fkey;
alter table evidence.claim_paper drop constraint claim_paper_claim_id_fkey;
alter table evidence.claim_paper drop constraint claim_paper_paper_id_fkey;
alter table evidence.claim_talk drop constraint claim_talk_claim_id_fkey;
alter table evidence.claim_talk drop constraint claim_talk_talk_id_fkey;
alter table evidence.claim_video drop constraint claim_video_claim_id_fkey;
alter table evidence.claim_video drop constraint claim_video_video_id_fkey;
alter table evidence.claim_product drop constraint claim_product_claim_id_fkey;
alter table evidence.claim_product drop constraint claim_product_product_id_fkey;
alter table evidence.claim_concept drop constraint claim_concept_claim_id_fkey;
alter table evidence.claim_concept drop constraint claim_concept_concept_id_fkey;
alter table evidence.claim_dataset drop constraint claim_dataset_claim_id_fkey;
alter table evidence.claim_dataset drop constraint claim_dataset_dataset_id_fkey;
alter table evidence.claim_benchmark drop constraint claim_benchmark_claim_id_fkey;
alter table evidence.claim_benchmark drop constraint claim_benchmark_benchmark_id_fkey;
alter table evidence.claim_ai_model_version drop constraint claim_ai_model_version_claim_id_fkey;
alter table evidence.claim_ai_model_version drop constraint claim_ai_model_version_ai_model_version_id_fkey;
alter table ranking.metric_observation drop constraint metric_observation_dataset_id_fkey;
alter table evidence.claim_mcp_server_version drop constraint claim_mcp_server_version_claim_id_fkey;
alter table evidence.claim_mcp_server_version drop constraint claim_mcp_server_version_mcp_server_version_id_fkey;
alter table evidence.claim_agent_skill_version drop constraint claim_agent_skill_version_claim_id_fkey;
alter table evidence.claim_agent_skill_version drop constraint claim_agent_skill_version_agent_skill_version_id_fkey;
alter table evidence.claim_protocol_version drop constraint claim_protocol_version_claim_id_fkey;
alter table evidence.claim_protocol_version drop constraint claim_protocol_version_ai_protocol_version_id_fkey;
alter table ranking.metric_observation drop constraint metric_observation_benchmark_id_fkey;
alter table ranking.metric_observation drop constraint metric_observation_talk_id_fkey;
alter table ranking.metric_observation drop constraint metric_observation_ai_model_id_fkey;
alter table ranking.metric_observation drop constraint metric_observation_raw_capture_id_fkey;
alter table evidence.claim_technical_record drop constraint claim_technical_record_claim_id_fkey;
alter table evidence.claim_technical_record drop constraint claim_technical_record_technical_problem_id_fkey;
alter table evidence.claim_technical_record drop constraint claim_technical_record_solution_pattern_id_fkey;
alter table evidence.claim_technical_record drop constraint claim_technical_record_advanced_usage_pattern_id_fkey;
alter table evidence.claim_technical_record drop constraint claim_technical_record_implementation_example_id_fkey;
alter table evidence.claim_technical_record drop constraint claim_technical_record_failure_mode_id_fkey;
alter table evidence.claim_technical_record drop constraint claim_technical_record_benchmark_result_id_fkey;
alter table evidence.claim_technical_record drop constraint claim_technical_record_compatibility_constraint_id_fkey;
alter table evidence.claim_technical_record drop constraint claim_technical_record_operational_practice_id_fkey;
alter table evidence.claim_technical_record drop constraint claim_technical_record_security_consideration_id_fkey;
alter table corpus.case_study drop constraint case_study_subject_organization_id_fkey;
alter table corpus.case_study drop constraint case_study_subject_product_id_fkey;
alter table corpus.case_study drop constraint case_study_merged_into_id_fkey;
alter table corpus.case_study drop constraint case_study_created_by_receipt_id_fkey;
alter table corpus.case_study drop constraint case_study_updated_by_receipt_id_fkey;
alter table staging.candidate_case_study drop constraint candidate_case_study_candidate_id_fkey;
alter table staging.candidate_case_study drop constraint candidate_case_study_candidate_id_candidate_kind_fkey;
alter table staging.identity_match drop constraint identity_match_case_study_id_fkey;
alter table evidence.claim_case_study drop constraint claim_case_study_claim_id_fkey;
alter table evidence.claim_case_study drop constraint claim_case_study_case_study_id_fkey;
alter table ranking.metric_observation drop constraint metric_observation_case_study_id_fkey;
alter table evidence.source_query drop constraint source_query_mission_id_fkey;
alter table evidence.source_query drop constraint source_query_work_item_id_fkey;
alter table evidence.source_query drop constraint source_query_attempt_id_fkey;
alter table evidence.source_query drop constraint source_query_response_artifact_id_fkey;
alter table evidence.source_retrieval drop constraint source_retrieval_query_id_fkey;
alter table evidence.source_retrieval drop constraint source_retrieval_source_id_fkey;
alter table evidence.source_retrieval drop constraint source_retrieval_capture_id_fkey;
alter table evidence.source_retrieval drop constraint source_retrieval_work_item_id_fkey;
alter table evidence.source_retrieval drop constraint source_retrieval_attempt_id_fkey;
alter table corpus.organization_relationship drop constraint organization_relationship_created_by_receipt_id_fkey;
alter table evidence.source_support drop constraint source_support_retrieval_id_fkey;
alter table evidence.source_support drop constraint source_support_work_item_id_fkey;
alter table evidence.source_support drop constraint source_support_locator_id_fkey;
alter table corpus.organization_relationship drop constraint organization_relationship_from_organization_id_fkey;
alter table corpus.organization_relationship drop constraint organization_relationship_to_organization_id_fkey;
alter table corpus.organization_relationship drop constraint organization_relationship_provenance_claim_id_fkey;
alter table corpus.organization_product_relationship drop constraint organization_product_relationship_organization_id_fkey;
alter table corpus.organization_product_relationship drop constraint organization_product_relationship_product_id_fkey;
alter table corpus.organization_product_relationship drop constraint organization_product_relationship_provenance_claim_id_fkey;
alter table corpus.organization_product_relationship drop constraint organization_product_relationship_created_by_receipt_id_fkey;
alter table corpus.product_family drop constraint product_family_vendor_organization_id_fkey;
alter table corpus.product_family drop constraint product_family_merged_into_id_fkey;
alter table corpus.product_family drop constraint product_family_created_by_receipt_id_fkey;
alter table corpus.product_family drop constraint product_family_updated_by_receipt_id_fkey;
alter table corpus.product_family_member drop constraint product_family_member_product_family_id_fkey;
alter table corpus.product_family_member drop constraint product_family_member_product_id_fkey;
alter table corpus.product_family_member drop constraint product_family_member_provenance_claim_id_fkey;
alter table corpus.product_family_member drop constraint product_family_member_created_by_receipt_id_fkey;
alter table corpus.product_version drop constraint product_version_product_id_fkey;
alter table corpus.product_version drop constraint product_version_created_by_receipt_id_fkey;
alter table corpus.product_feature drop constraint product_feature_product_id_fkey;
alter table corpus.product_feature drop constraint product_feature_introduced_in_version_id_fkey;
alter table corpus.product_feature drop constraint product_feature_retired_in_version_id_fkey;
alter table corpus.product_feature drop constraint product_feature_provenance_claim_id_fkey;
alter table corpus.product_feature drop constraint product_feature_created_by_receipt_id_fkey;
alter table corpus.product_backed_by_repository drop constraint product_backed_by_repository_product_id_fkey;
alter table corpus.product_backed_by_repository drop constraint product_backed_by_repository_repository_id_fkey;
alter table corpus.product_backed_by_repository drop constraint product_backed_by_repository_provenance_claim_id_fkey;
alter table corpus.product_backed_by_repository drop constraint product_backed_by_repository_created_by_receipt_id_fkey;
alter table corpus.ai_model_relationship drop constraint ai_model_relationship_from_ai_model_id_fkey;
alter table corpus.ai_model_relationship drop constraint ai_model_relationship_to_ai_model_id_fkey;
alter table corpus.ai_model_relationship drop constraint ai_model_relationship_provenance_claim_id_fkey;
alter table corpus.ai_model_relationship drop constraint ai_model_relationship_created_by_receipt_id_fkey;
alter table corpus.ai_protocol_relationship drop constraint ai_protocol_relationship_from_ai_protocol_id_fkey;
alter table corpus.ai_protocol_relationship drop constraint ai_protocol_relationship_to_ai_protocol_id_fkey;
alter table corpus.ai_protocol_relationship drop constraint ai_protocol_relationship_provenance_claim_id_fkey;
alter table corpus.ai_protocol_relationship drop constraint ai_protocol_relationship_created_by_receipt_id_fkey;
alter table corpus.repository_maintained_by_organization drop constraint repository_maintained_by_organization_repository_id_fkey;
alter table corpus.repository_maintained_by_organization drop constraint repository_maintained_by_organization_organization_id_fkey;
alter table corpus.repository_maintained_by_organization drop constraint repository_maintained_by_organization_provenance_claim_id_fkey;
alter table corpus.repository_maintained_by_organization drop constraint repository_maintained_by_organizatio_created_by_receipt_id_fkey;
alter table corpus.paper_introduces_model drop constraint paper_introduces_model_paper_id_fkey;
alter table corpus.paper_introduces_model drop constraint paper_introduces_model_ai_model_id_fkey;
alter table corpus.paper_introduces_model drop constraint paper_introduces_model_provenance_claim_id_fkey;
alter table corpus.paper_introduces_model drop constraint paper_introduces_model_created_by_receipt_id_fkey;
alter table corpus.benchmark_evaluates_model_version drop constraint benchmark_evaluates_model_version_benchmark_id_fkey;
alter table corpus.benchmark_evaluates_model_version drop constraint benchmark_evaluates_model_version_ai_model_version_id_fkey;
alter table corpus.benchmark_evaluates_model_version drop constraint benchmark_evaluates_model_version_provenance_claim_id_fkey;
alter table corpus.benchmark_evaluates_model_version drop constraint benchmark_evaluates_model_version_created_by_receipt_id_fkey;
alter table corpus.benchmark_uses_dataset drop constraint benchmark_uses_dataset_benchmark_id_fkey;
alter table corpus.benchmark_uses_dataset drop constraint benchmark_uses_dataset_dataset_id_fkey;
alter table corpus.benchmark_uses_dataset drop constraint benchmark_uses_dataset_provenance_claim_id_fkey;
alter table corpus.benchmark_uses_dataset drop constraint benchmark_uses_dataset_created_by_receipt_id_fkey;
alter table corpus.case_study_uses_model_version drop constraint case_study_uses_model_version_case_study_id_fkey;
alter table corpus.case_study_uses_model_version drop constraint case_study_uses_model_version_ai_model_version_id_fkey;
alter table corpus.case_study_uses_model_version drop constraint case_study_uses_model_version_provenance_claim_id_fkey;
alter table corpus.case_study_uses_model_version drop constraint case_study_uses_model_version_created_by_receipt_id_fkey;
alter table corpus.case_study_uses_library drop constraint case_study_uses_library_case_study_id_fkey;
alter table corpus.case_study_uses_library drop constraint case_study_uses_library_library_id_fkey;
alter table corpus.case_study_uses_library drop constraint case_study_uses_library_provenance_claim_id_fkey;
alter table corpus.case_study_uses_library drop constraint case_study_uses_library_created_by_receipt_id_fkey;
alter table corpus.case_study_references_benchmark drop constraint case_study_references_benchmark_case_study_id_fkey;
alter table corpus.case_study_references_benchmark drop constraint case_study_references_benchmark_benchmark_id_fkey;
alter table corpus.case_study_references_benchmark drop constraint case_study_references_benchmark_provenance_claim_id_fkey;
alter table corpus.case_study_references_benchmark drop constraint case_study_references_benchmark_created_by_receipt_id_fkey;
alter table evidence.claim_product_version drop constraint claim_product_version_claim_id_fkey;
alter table evidence.claim_product_version drop constraint claim_product_version_product_version_id_fkey;
alter table retrieval.chunk_entity_mention drop constraint chunk_entity_mention_tenant_id_chunk_id_fkey;
alter table retrieval.chunk_entity_mention drop constraint chunk_entity_mention_tenant_id_entity_target_id_fkey;
alter table retrieval.chunk_entity_mention drop constraint chunk_entity_mention_tenant_id_document_node_id_fkey;
alter table retrieval.chunk_claim_link drop constraint chunk_claim_link_tenant_id_chunk_id_fkey;
alter table retrieval.chunk_claim_link drop constraint chunk_claim_link_tenant_id_claim_id_fkey;
alter table retrieval.chunk_concept_link drop constraint chunk_concept_link_tenant_id_chunk_id_fkey;
alter table retrieval.chunk_concept_link drop constraint chunk_concept_link_tenant_id_concept_target_id_fkey;
alter table retrieval.chunk_citation_link drop constraint chunk_citation_link_tenant_id_citation_document_id_fkey;
alter table retrieval.chunk_citation_link drop constraint chunk_citation_link_tenant_id_citation_source_id_fkey;
alter table retrieval.chunk_relationship_evidence drop constraint chunk_relationship_evidence_tenant_id_chunk_id_fkey;
alter table retrieval.chunk_relationship_evidence drop constraint chunk_relationship_evidence_tenant_id_relationship_target__fkey;
drop table corpus.agent_skill,
corpus.agent_skill_requires_mcp_server,
corpus.agent_skill_targets_library,
corpus.agent_skill_version,
corpus.ai_model,
corpus.ai_model_availability_fact,
corpus.ai_model_relationship,
corpus.ai_model_released_by_organization,
corpus.ai_model_version,
corpus.ai_protocol,
corpus.ai_protocol_relationship,
corpus.ai_protocol_version,
corpus.benchmark,
corpus.benchmark_evaluates_model_version,
corpus.benchmark_uses_dataset,
corpus.case_study,
corpus.case_study_references_benchmark,
corpus.case_study_uses_library,
corpus.case_study_uses_model_version,
corpus.concept,
corpus.concept_alias,
corpus.dataset,
corpus.distribution_kind,
corpus.entity_merge,
corpus.library,
corpus.library_appeared_in_video,
corpus.library_backed_by_repository,
corpus.library_depends_on_library,
corpus.library_implements_protocol_version,
corpus.library_license_fact,
corpus.library_maintained_by_person,
corpus.library_maintenance_status_fact,
corpus.library_supports_model_version,
corpus.mcp_server,
corpus.mcp_server_backed_by_repository,
corpus.mcp_server_prompt,
corpus.mcp_server_registry_status_fact,
corpus.mcp_server_resource,
corpus.mcp_server_tool,
corpus.mcp_server_version,
corpus.mcp_server_wraps_product,
corpus.organization,
corpus.organization_identifier,
corpus.organization_product_relationship,
corpus.organization_relationship,
corpus.paper,
corpus.paper_appeared_in_talk,
corpus.paper_appeared_in_video,
corpus.paper_authored_by_person,
corpus.paper_introduces_model,
corpus.paper_retraction_fact,
corpus.person,
corpus.person_appeared_in_video,
corpus.person_created_agent_skill,
corpus.person_created_mcp_server,
corpus.person_employed_by_organization,
corpus.person_founded_organization,
corpus.person_identifier,
corpus.person_presented_at_talk,
corpus.product,
corpus.product_appeared_in_video,
corpus.product_backed_by_repository,
corpus.product_built_on_model_version,
corpus.product_family,
corpus.product_family_member,
corpus.product_feature,
corpus.product_implements_protocol_version,
corpus.product_version,
corpus.repository,
corpus.repository_alias,
corpus.repository_archival_fact,
corpus.repository_implements_paper,
corpus.repository_maintained_by_organization,
corpus.talk,
corpus.talk_explains_concept,
corpus.video,
evidence.claim_agent_skill_version,
evidence.claim_ai_model_version,
evidence.claim_benchmark,
evidence.claim_case_study,
evidence.claim_concept,
evidence.claim_dataset,
evidence.claim_library,
evidence.claim_mcp_server_version,
evidence.claim_organization,
evidence.claim_paper,
evidence.claim_person,
evidence.claim_product,
evidence.claim_product_version,
evidence.claim_protocol_version,
evidence.claim_repository,
evidence.claim_talk,
evidence.claim_technical_record,
evidence.claim_video,
evidence.source_query,
evidence.source_retrieval,
evidence.source_support,
knowledge.advanced_usage_pattern,
knowledge.benchmark_compares_libraries,
knowledge.benchmark_result,
knowledge.compatibility_constraint,
knowledge.failure_mode,
knowledge.failure_mode_affects_library_version,
knowledge.failure_mode_affects_mcp_server,
knowledge.implementation_demonstrates_pattern,
knowledge.implementation_example,
knowledge.library_addresses_problem,
knowledge.operational_practice,
knowledge.paper_supports_solution,
knowledge.problem_solved_by_solution,
knowledge.repository_contains_implementation,
knowledge.security_consideration,
knowledge.solution_applies_under_constraint,
knowledge.solution_pattern,
knowledge.solution_uses_protocol_version,
knowledge.talk_explains_pattern,
knowledge.technical_problem,
ranking.feature_value,
ranking.metric_definition,
ranking.metric_definition_version,
ranking.metric_observation,
ranking.ranking_result,
retrieval.chunk_citation_link,
retrieval.chunk_claim_link,
retrieval.chunk_concept_link,
retrieval.chunk_entity_mention,
retrieval.chunk_relationship_evidence,
retrieval.projection_target,
staging.candidate,
staging.candidate_agent_skill,
staging.candidate_ai_model,
staging.candidate_ai_protocol,
staging.candidate_benchmark,
staging.candidate_case_study,
staging.candidate_concept,
staging.candidate_dataset,
staging.candidate_library,
staging.candidate_mcp_server,
staging.candidate_organization,
staging.candidate_paper,
staging.candidate_person,
staging.candidate_product,
staging.candidate_repository,
staging.candidate_talk,
staging.candidate_technical_record,
staging.candidate_video,
staging.identity_match,
staging.mention,
staging.resolution_decision,
staging.vetting_decision restrict;
alter table retrieval.vector_item drop column if exists source_kind;
alter table retrieval.vector_item drop column if exists claim_id;
alter table retrieval.vector_item drop column if exists technical_problem_id;
alter table retrieval.vector_item drop column if exists solution_pattern_id;
alter table retrieval.vector_item drop column if exists advanced_usage_pattern_id;
alter table retrieval.vector_item drop column if exists implementation_example_id;
alter table retrieval.vector_item drop column if exists failure_mode_id;
alter table retrieval.vector_item drop column if exists benchmark_result_id;
alter table retrieval.vector_item drop column if exists compatibility_constraint_id;
alter table retrieval.vector_item drop column if exists operational_practice_id;
alter table retrieval.vector_item drop column if exists security_consideration_id;
alter table retrieval.vector_item drop column if exists report_version_id;
alter table retrieval.vector_item drop column if exists video_id;
alter table retrieval.vector_item drop column if exists talk_id;
alter table retrieval.vector_item drop column if exists embedding;
drop trigger assignment_term_target_scope on taxonomy.assignment;
alter table taxonomy.assignment drop column target_kind;
alter table taxonomy.assignment drop column library_id;
alter table taxonomy.assignment drop column repository_id;
alter table taxonomy.assignment drop column person_id;
alter table taxonomy.assignment drop column organization_id;
alter table taxonomy.assignment drop column paper_id;
alter table taxonomy.assignment drop column talk_id;
alter table taxonomy.assignment drop column video_id;
alter table taxonomy.assignment drop column product_id;
alter table taxonomy.assignment drop column concept_id;
alter table taxonomy.assignment drop column ai_model_id;
alter table taxonomy.assignment drop column ai_protocol_id;
alter table taxonomy.assignment drop column mcp_server_id;
alter table taxonomy.assignment drop column agent_skill_id;
alter table taxonomy.assignment drop column technical_problem_id;
alter table taxonomy.assignment drop column solution_pattern_id;
alter table taxonomy.assignment drop column advanced_usage_pattern_id;
alter table taxonomy.assignment drop column failure_mode_id;
alter table taxonomy.assignment drop column case_study_id;
alter table taxonomy.assignment drop column dataset_id;
alter table taxonomy.assignment drop column benchmark_id;
commit;
