-- Knowledge model v2: grants_rls. See docs/knowledge-model/FINAL-RECOMMENDATION.md.
begin;
set local lock_timeout = '15s';

-- Scope new foreign keys by tenant, including child tables whose abbreviated design used id alone.
do $$ declare t text; r record; target text; begin
 foreach t in array array['taxonomy.relationship_kind','temporal.stream_kind','temporal.event_kind','content.document_type','content.transformation_kind','evidence.search_provider','evidence.capture_method','corpus.license','corpus.distribution_kind','corpus.entity','corpus.entity_alias','corpus.entity_identifier','corpus.entity_merge','corpus.person','corpus.organization','corpus.product','corpus.product_version','corpus.product_feature','corpus.ai_model','corpus.ai_model_version','corpus.model_offering','corpus.technique','corpus.dataset','corpus.benchmark','corpus.benchmark_run','corpus.repository','corpus.library','corpus.library_release','corpus.mcp_server','corpus.agent_skill','corpus.ai_protocol','corpus.ai_protocol_version','corpus.ai_protocol_feature','corpus.paper','corpus.story','corpus.case_study','corpus.concept','corpus.funding_round','corpus.corporate_transaction','corpus.registry','corpus.security_advisory','corpus.compute_device','corpus.compute_offering','corpus.media_platform','corpus.media_channel','corpus.event_series','corpus.industry_event','corpus.media_series','corpus.media_work','corpus.talk','corpus.repository_revision','corpus.repository_module','corpus.repository_file','corpus.ai_model_version_spec','corpus.mcp_server_surface','corpus.registry_listing','corpus.relationship','corpus.media_appearance','temporal.knowledge_head','temporal.knowledge_batch','temporal.extent','temporal.stream','temporal.event','temporal.event_occurrence','temporal.segment','evidence.source_query','evidence.provider_result','evidence.source_encounter','evidence.extraction_run','evidence.extraction_record','evidence.attribution','evidence.claim_subject','evidence.claim_record','evidence.segment_support','content.document_about_entity','content.document_summary','content.document_summary_source','knowledge.record','knowledge.technical_problem','knowledge.solution_pattern','knowledge.advanced_usage_pattern','knowledge.implementation_example','knowledge.failure_mode','knowledge.benchmark_result','knowledge.compatibility_constraint','knowledge.operational_practice','knowledge.security_consideration','knowledge.record_entity_link','retrieval.projection_target','retrieval.chunk_entity_mention','retrieval.chunk_claim_link','retrieval.chunk_relationship_evidence','ranking.metric_definition','ranking.metric_definition_version','ranking.metric_observation','ranking.feature_value','ranking.ranking_result','staging.candidate','staging.identity_match','staging.resolution_decision','staging.vetting_decision'] loop
  if exists(select 1 from pg_attribute where attrelid=t::regclass and attname='tenant_id' and not attisdropped) then
   execute format('alter table %s enable row level security',t);
   execute format('create policy km_tenant_access on %s for all to executor_service,pipeline_agent,verifier_agent,control_plane using(tenant_id=util.current_tenant_id()) with check(tenant_id=util.current_tenant_id())',t);
   if exists(select 1 from pg_attribute where attrelid=t::regclass and attname='id' and not attisdropped) and not exists(select 1 from pg_constraint where conrelid=t::regclass and contype='u' and pg_get_constraintdef(oid)='UNIQUE (tenant_id, id)') then execute format('alter table %s add unique(tenant_id,id)',t); end if;
  end if;
 end loop;
 foreach t in array array['taxonomy.relationship_kind','temporal.stream_kind','temporal.event_kind','content.document_type','content.transformation_kind','evidence.search_provider','evidence.capture_method','corpus.license','corpus.distribution_kind','corpus.entity','corpus.entity_alias','corpus.entity_identifier','corpus.entity_merge','corpus.person','corpus.organization','corpus.product','corpus.product_version','corpus.product_feature','corpus.ai_model','corpus.ai_model_version','corpus.model_offering','corpus.technique','corpus.dataset','corpus.benchmark','corpus.benchmark_run','corpus.repository','corpus.library','corpus.library_release','corpus.mcp_server','corpus.agent_skill','corpus.ai_protocol','corpus.ai_protocol_version','corpus.ai_protocol_feature','corpus.paper','corpus.story','corpus.case_study','corpus.concept','corpus.funding_round','corpus.corporate_transaction','corpus.registry','corpus.security_advisory','corpus.compute_device','corpus.compute_offering','corpus.media_platform','corpus.media_channel','corpus.event_series','corpus.industry_event','corpus.media_series','corpus.media_work','corpus.talk','corpus.repository_revision','corpus.repository_module','corpus.repository_file','corpus.ai_model_version_spec','corpus.mcp_server_surface','corpus.registry_listing','corpus.relationship','corpus.media_appearance','temporal.knowledge_head','temporal.knowledge_batch','temporal.extent','temporal.stream','temporal.event','temporal.event_occurrence','temporal.segment','evidence.source_query','evidence.provider_result','evidence.source_encounter','evidence.extraction_run','evidence.extraction_record','evidence.attribution','evidence.claim_subject','evidence.claim_record','evidence.segment_support','content.document_about_entity','content.document_summary','content.document_summary_source','knowledge.record','knowledge.technical_problem','knowledge.solution_pattern','knowledge.advanced_usage_pattern','knowledge.implementation_example','knowledge.failure_mode','knowledge.benchmark_result','knowledge.compatibility_constraint','knowledge.operational_practice','knowledge.security_consideration','knowledge.record_entity_link','retrieval.projection_target','retrieval.chunk_entity_mention','retrieval.chunk_claim_link','retrieval.chunk_relationship_evidence','ranking.metric_definition','ranking.metric_definition_version','ranking.metric_observation','ranking.feature_value','ranking.ranking_result','staging.candidate','staging.identity_match','staging.resolution_decision','staging.vetting_decision'] loop
  for r in select c.oid,c.confrelid,c.conrelid,a.attname column_name from pg_constraint c join pg_attribute a on a.attrelid=c.conrelid and a.attnum=c.conkey[1] where c.conrelid=t::regclass and c.contype='f' and cardinality(c.conkey)=1 and exists(select 1 from pg_attribute where attrelid=c.conrelid and attname='tenant_id' and not attisdropped) and exists(select 1 from pg_constraint u where u.conrelid=c.confrelid and u.contype='u' and pg_get_constraintdef(u.oid)='UNIQUE (tenant_id, id)') loop
   execute format('alter table %s add foreign key(tenant_id,%I) references %s(tenant_id,id) deferrable initially deferred',r.conrelid::regclass,r.column_name,r.confrelid::regclass);
  end loop;
 end loop;
end $$;
-- Privileges are assigned table-by-table: existing verification grants remain untouched.
revoke all on schema temporal from public,anon,authenticated;
grant usage on schema temporal to executor_service,pipeline_agent,verifier_agent,control_plane;
grant usage on schema corpus,knowledge,staging,ranking,content,retrieval,evidence,taxonomy,api to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table taxonomy.relationship_kind from public,anon,authenticated,app_reader;
grant select on table taxonomy.relationship_kind to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table temporal.stream_kind from public,anon,authenticated,app_reader;
grant select on table temporal.stream_kind to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table temporal.event_kind from public,anon,authenticated,app_reader;
grant select on table temporal.event_kind to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table content.document_type from public,anon,authenticated,app_reader;
grant select on table content.document_type to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table content.transformation_kind from public,anon,authenticated,app_reader;
grant select on table content.transformation_kind to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table evidence.search_provider from public,anon,authenticated,app_reader;
grant select on table evidence.search_provider to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table evidence.capture_method from public,anon,authenticated,app_reader;
grant select on table evidence.capture_method to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.license from public,anon,authenticated,app_reader;
grant select on table corpus.license to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.distribution_kind from public,anon,authenticated,app_reader;
grant select on table corpus.distribution_kind to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.entity from public,anon,authenticated,app_reader;
grant select on table corpus.entity to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.entity_alias from public,anon,authenticated,app_reader;
grant select on table corpus.entity_alias to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.entity_identifier from public,anon,authenticated,app_reader;
grant select on table corpus.entity_identifier to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.entity_merge from public,anon,authenticated,app_reader;
grant select on table corpus.entity_merge to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.person from public,anon,authenticated,app_reader;
grant select on table corpus.person to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.organization from public,anon,authenticated,app_reader;
grant select on table corpus.organization to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.product from public,anon,authenticated,app_reader;
grant select on table corpus.product to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.product_version from public,anon,authenticated,app_reader;
grant select on table corpus.product_version to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.product_feature from public,anon,authenticated,app_reader;
grant select on table corpus.product_feature to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.ai_model from public,anon,authenticated,app_reader;
grant select on table corpus.ai_model to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.ai_model_version from public,anon,authenticated,app_reader;
grant select on table corpus.ai_model_version to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.model_offering from public,anon,authenticated,app_reader;
grant select on table corpus.model_offering to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.technique from public,anon,authenticated,app_reader;
grant select on table corpus.technique to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.dataset from public,anon,authenticated,app_reader;
grant select on table corpus.dataset to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.benchmark from public,anon,authenticated,app_reader;
grant select on table corpus.benchmark to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.benchmark_run from public,anon,authenticated,app_reader;
grant select on table corpus.benchmark_run to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.repository from public,anon,authenticated,app_reader;
grant select on table corpus.repository to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.library from public,anon,authenticated,app_reader;
grant select on table corpus.library to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.library_release from public,anon,authenticated,app_reader;
grant select on table corpus.library_release to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.mcp_server from public,anon,authenticated,app_reader;
grant select on table corpus.mcp_server to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.agent_skill from public,anon,authenticated,app_reader;
grant select on table corpus.agent_skill to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.ai_protocol from public,anon,authenticated,app_reader;
grant select on table corpus.ai_protocol to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.ai_protocol_version from public,anon,authenticated,app_reader;
grant select on table corpus.ai_protocol_version to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.ai_protocol_feature from public,anon,authenticated,app_reader;
grant select on table corpus.ai_protocol_feature to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.paper from public,anon,authenticated,app_reader;
grant select on table corpus.paper to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.story from public,anon,authenticated,app_reader;
grant select on table corpus.story to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.case_study from public,anon,authenticated,app_reader;
grant select on table corpus.case_study to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.concept from public,anon,authenticated,app_reader;
grant select on table corpus.concept to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.funding_round from public,anon,authenticated,app_reader;
grant select on table corpus.funding_round to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.corporate_transaction from public,anon,authenticated,app_reader;
grant select on table corpus.corporate_transaction to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.registry from public,anon,authenticated,app_reader;
grant select on table corpus.registry to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.security_advisory from public,anon,authenticated,app_reader;
grant select on table corpus.security_advisory to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.compute_device from public,anon,authenticated,app_reader;
grant select on table corpus.compute_device to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.compute_offering from public,anon,authenticated,app_reader;
grant select on table corpus.compute_offering to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.media_platform from public,anon,authenticated,app_reader;
grant select on table corpus.media_platform to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.media_channel from public,anon,authenticated,app_reader;
grant select on table corpus.media_channel to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.event_series from public,anon,authenticated,app_reader;
grant select on table corpus.event_series to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.industry_event from public,anon,authenticated,app_reader;
grant select on table corpus.industry_event to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.media_series from public,anon,authenticated,app_reader;
grant select on table corpus.media_series to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.media_work from public,anon,authenticated,app_reader;
grant select on table corpus.media_work to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.talk from public,anon,authenticated,app_reader;
grant select on table corpus.talk to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.repository_revision from public,anon,authenticated,app_reader;
grant select on table corpus.repository_revision to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.repository_module from public,anon,authenticated,app_reader;
grant select on table corpus.repository_module to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.repository_file from public,anon,authenticated,app_reader;
grant select on table corpus.repository_file to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.ai_model_version_spec from public,anon,authenticated,app_reader;
grant select on table corpus.ai_model_version_spec to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.mcp_server_surface from public,anon,authenticated,app_reader;
grant select on table corpus.mcp_server_surface to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.registry_listing from public,anon,authenticated,app_reader;
grant select on table corpus.registry_listing to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.relationship from public,anon,authenticated,app_reader;
grant select on table corpus.relationship to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table corpus.media_appearance from public,anon,authenticated,app_reader;
grant select on table corpus.media_appearance to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table temporal.knowledge_head from public,anon,authenticated,app_reader;
grant select on table temporal.knowledge_head to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table temporal.knowledge_batch from public,anon,authenticated,app_reader;
grant select on table temporal.knowledge_batch to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table temporal.extent from public,anon,authenticated,app_reader;
grant select on table temporal.extent to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table temporal.stream from public,anon,authenticated,app_reader;
grant select on table temporal.stream to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table temporal.event from public,anon,authenticated,app_reader;
grant select on table temporal.event to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table temporal.event_occurrence from public,anon,authenticated,app_reader;
grant select on table temporal.event_occurrence to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table temporal.segment from public,anon,authenticated,app_reader;
grant select on table temporal.segment to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table evidence.source_query from public,anon,authenticated,app_reader;
grant select on table evidence.source_query to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table evidence.provider_result from public,anon,authenticated,app_reader;
grant select on table evidence.provider_result to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table evidence.source_encounter from public,anon,authenticated,app_reader;
grant select on table evidence.source_encounter to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table evidence.extraction_run from public,anon,authenticated,app_reader;
grant select on table evidence.extraction_run to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table evidence.extraction_record from public,anon,authenticated,app_reader;
grant select on table evidence.extraction_record to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table evidence.attribution from public,anon,authenticated,app_reader;
grant select on table evidence.attribution to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table evidence.claim_subject from public,anon,authenticated,app_reader;
grant select on table evidence.claim_subject to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table evidence.claim_record from public,anon,authenticated,app_reader;
grant select on table evidence.claim_record to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table evidence.segment_support from public,anon,authenticated,app_reader;
grant select on table evidence.segment_support to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table content.document_about_entity from public,anon,authenticated,app_reader;
grant select on table content.document_about_entity to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table content.document_summary from public,anon,authenticated,app_reader;
grant select on table content.document_summary to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table content.document_summary_source from public,anon,authenticated,app_reader;
grant select on table content.document_summary_source to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table knowledge.record from public,anon,authenticated,app_reader;
grant select on table knowledge.record to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table knowledge.technical_problem from public,anon,authenticated,app_reader;
grant select on table knowledge.technical_problem to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table knowledge.solution_pattern from public,anon,authenticated,app_reader;
grant select on table knowledge.solution_pattern to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table knowledge.advanced_usage_pattern from public,anon,authenticated,app_reader;
grant select on table knowledge.advanced_usage_pattern to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table knowledge.implementation_example from public,anon,authenticated,app_reader;
grant select on table knowledge.implementation_example to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table knowledge.failure_mode from public,anon,authenticated,app_reader;
grant select on table knowledge.failure_mode to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table knowledge.benchmark_result from public,anon,authenticated,app_reader;
grant select on table knowledge.benchmark_result to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table knowledge.compatibility_constraint from public,anon,authenticated,app_reader;
grant select on table knowledge.compatibility_constraint to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table knowledge.operational_practice from public,anon,authenticated,app_reader;
grant select on table knowledge.operational_practice to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table knowledge.security_consideration from public,anon,authenticated,app_reader;
grant select on table knowledge.security_consideration to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table knowledge.record_entity_link from public,anon,authenticated,app_reader;
grant select on table knowledge.record_entity_link to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table retrieval.projection_target from public,anon,authenticated,app_reader;
grant select on table retrieval.projection_target to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table retrieval.chunk_entity_mention from public,anon,authenticated,app_reader;
grant select on table retrieval.chunk_entity_mention to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table retrieval.chunk_claim_link from public,anon,authenticated,app_reader;
grant select on table retrieval.chunk_claim_link to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table retrieval.chunk_relationship_evidence from public,anon,authenticated,app_reader;
grant select on table retrieval.chunk_relationship_evidence to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table ranking.metric_definition from public,anon,authenticated,app_reader;
grant select on table ranking.metric_definition to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table ranking.metric_definition_version from public,anon,authenticated,app_reader;
grant select on table ranking.metric_definition_version to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table ranking.metric_observation from public,anon,authenticated,app_reader;
grant select on table ranking.metric_observation to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table ranking.feature_value from public,anon,authenticated,app_reader;
grant select on table ranking.feature_value to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table ranking.ranking_result from public,anon,authenticated,app_reader;
grant select on table ranking.ranking_result to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table staging.candidate from public,anon,authenticated,app_reader;
grant select on table staging.candidate to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table staging.identity_match from public,anon,authenticated,app_reader;
grant select on table staging.identity_match to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table staging.resolution_decision from public,anon,authenticated,app_reader;
grant select on table staging.resolution_decision to executor_service,pipeline_agent,verifier_agent,control_plane;
revoke all on table staging.vetting_decision from public,anon,authenticated,app_reader;
grant select on table staging.vetting_decision to executor_service,pipeline_agent,verifier_agent,control_plane;
grant insert,update on table content.document_type to pipeline_agent,executor_service;
grant insert,update on table content.transformation_kind to pipeline_agent,executor_service;
grant insert,update on table evidence.search_provider to pipeline_agent,executor_service;
grant insert,update on table evidence.capture_method to pipeline_agent,executor_service;
grant insert,update on table evidence.source_query to pipeline_agent,executor_service;
grant insert,update on table evidence.provider_result to pipeline_agent,executor_service;
grant insert,update on table evidence.source_encounter to pipeline_agent,executor_service;
grant insert,update on table evidence.extraction_run to pipeline_agent,executor_service;
grant insert,update on table evidence.extraction_record to pipeline_agent,executor_service;
grant insert,update on table evidence.attribution to pipeline_agent,executor_service;
grant insert,update on table evidence.claim_subject to pipeline_agent,executor_service;
grant insert,update on table evidence.claim_record to pipeline_agent,executor_service;
grant insert,update on table content.document_about_entity to pipeline_agent,executor_service;
grant insert,update on table content.document_summary to pipeline_agent,executor_service;
grant insert,update on table content.document_summary_source to pipeline_agent,executor_service;
grant insert,update on table retrieval.projection_target to pipeline_agent,executor_service;
grant insert,update on table retrieval.chunk_entity_mention to pipeline_agent,executor_service;
grant insert,update on table retrieval.chunk_claim_link to pipeline_agent,executor_service;
grant insert,update on table retrieval.chunk_relationship_evidence to pipeline_agent,executor_service;
grant insert,update on table staging.candidate to pipeline_agent,executor_service;
grant insert,update on table staging.identity_match to pipeline_agent,executor_service;
grant insert,update on table staging.resolution_decision to pipeline_agent,executor_service;
grant insert,update on table staging.vetting_decision to pipeline_agent,executor_service;
grant insert,update on table corpus.license to executor_service;
grant insert,update on table corpus.distribution_kind to executor_service;
grant insert,update on table corpus.entity to executor_service;
grant insert,update on table corpus.entity_alias to executor_service;
grant insert,update on table corpus.entity_identifier to executor_service;
grant insert,update on table corpus.entity_merge to executor_service;
grant insert,update on table corpus.person to executor_service;
grant insert,update on table corpus.organization to executor_service;
grant insert,update on table corpus.product to executor_service;
grant insert,update on table corpus.product_version to executor_service;
grant insert,update on table corpus.product_feature to executor_service;
grant insert,update on table corpus.ai_model to executor_service;
grant insert,update on table corpus.ai_model_version to executor_service;
grant insert,update on table corpus.model_offering to executor_service;
grant insert,update on table corpus.technique to executor_service;
grant insert,update on table corpus.dataset to executor_service;
grant insert,update on table corpus.benchmark to executor_service;
grant insert,update on table corpus.benchmark_run to executor_service;
grant insert,update on table corpus.repository to executor_service;
grant insert,update on table corpus.library to executor_service;
grant insert,update on table corpus.library_release to executor_service;
grant insert,update on table corpus.mcp_server to executor_service;
grant insert,update on table corpus.agent_skill to executor_service;
grant insert,update on table corpus.ai_protocol to executor_service;
grant insert,update on table corpus.ai_protocol_version to executor_service;
grant insert,update on table corpus.ai_protocol_feature to executor_service;
grant insert,update on table corpus.paper to executor_service;
grant insert,update on table corpus.story to executor_service;
grant insert,update on table corpus.case_study to executor_service;
grant insert,update on table corpus.concept to executor_service;
grant insert,update on table corpus.funding_round to executor_service;
grant insert,update on table corpus.corporate_transaction to executor_service;
grant insert,update on table corpus.registry to executor_service;
grant insert,update on table corpus.security_advisory to executor_service;
grant insert,update on table corpus.compute_device to executor_service;
grant insert,update on table corpus.compute_offering to executor_service;
grant insert,update on table corpus.media_platform to executor_service;
grant insert,update on table corpus.media_channel to executor_service;
grant insert,update on table corpus.event_series to executor_service;
grant insert,update on table corpus.industry_event to executor_service;
grant insert,update on table corpus.media_series to executor_service;
grant insert,update on table corpus.media_work to executor_service;
grant insert,update on table corpus.talk to executor_service;
grant insert,update on table corpus.repository_revision to executor_service;
grant insert,update on table corpus.repository_module to executor_service;
grant insert,update on table corpus.repository_file to executor_service;
grant insert,update on table corpus.ai_model_version_spec to executor_service;
grant insert,update on table corpus.mcp_server_surface to executor_service;
grant insert,update on table corpus.registry_listing to executor_service;
grant insert,update on table corpus.media_appearance to executor_service;
grant insert,update on table knowledge.record to executor_service;
grant insert,update on table knowledge.technical_problem to executor_service;
grant insert,update on table knowledge.solution_pattern to executor_service;
grant insert,update on table knowledge.advanced_usage_pattern to executor_service;
grant insert,update on table knowledge.implementation_example to executor_service;
grant insert,update on table knowledge.failure_mode to executor_service;
grant insert,update on table knowledge.benchmark_result to executor_service;
grant insert,update on table knowledge.compatibility_constraint to executor_service;
grant insert,update on table knowledge.operational_practice to executor_service;
grant insert,update on table knowledge.security_consideration to executor_service;
grant insert,update on table knowledge.record_entity_link to executor_service;
grant insert,update on table ranking.metric_definition to executor_service;
grant insert,update on table ranking.metric_definition_version to executor_service;
grant insert,update on table ranking.metric_observation to executor_service;
grant insert,update on table ranking.feature_value to executor_service;
grant insert,update on table ranking.ranking_result to executor_service;
revoke insert,update,delete,truncate on all tables in schema temporal from public,anon,authenticated,service_role,executor_service,pipeline_agent,verifier_agent,control_plane,app_reader;
revoke insert,update,delete,truncate on corpus.relationship,evidence.segment_support from public,anon,authenticated,service_role,executor_service,pipeline_agent,verifier_agent,control_plane,app_reader;
revoke all on all functions in schema temporal from public,anon,authenticated,service_role,pipeline_agent,verifier_agent,control_plane,app_reader;
grant execute on all functions in schema temporal to executor_service;
revoke all on function corpus.check_relationship_kinds() from public,anon,authenticated;
revoke all on function content.check_summary_lineage() from public,anon,authenticated;
do $$ declare r record; begin
 for r in select p.oid::regprocedure signature from pg_proc p where p.pronamespace='api'::regnamespace and p.proname in ('resolve_entity','entity_at','relationships','entity_card','entity_timeline','what_changed','summary_evidence','evidence_packet','hybrid_knowledge_search_1536','leaderboard') loop
 execute format('revoke all on function %s from public,anon',r.signature);
 execute format('grant execute on function %s to app_reader,authenticated,executor_service,pipeline_agent,verifier_agent,control_plane,service_role',r.signature);
 end loop;
end $$;
grant select on api.entities,api.current_facts,api.current_relationships,api.events_current,api.library_profile,api.technical_record_search,api.review_queue to executor_service,pipeline_agent,verifier_agent,control_plane;
grant usage on schema api to app_reader,authenticated;


create function corpus.check_receipt_tenant() returns trigger language plpgsql set search_path='' as $$
begin
 if not exists(select 1 from orchestration.operation_receipt r join orchestration.operation_intent i on i.id=r.intent_id where r.id=new.created_by_receipt_id and i.tenant_id=new.tenant_id) then raise exception 'entity/record receipt tenant mismatch'; end if;
 return new;
end $$;
create trigger entity_receipt_tenant before insert or update on corpus.entity for each row execute function corpus.check_receipt_tenant();
create trigger record_receipt_tenant before insert or update on knowledge.record for each row execute function corpus.check_receipt_tenant();
create function corpus.check_repository_lineage() returns trigger language plpgsql set search_path='' as $$
begin
 if not exists(select 1 from corpus.repository_revision where id=new.revision_id and repository_id=new.repository_id and tenant_id=new.tenant_id) then raise exception 'file revision belongs to another repository'; end if;
 if new.module_id is not null and not exists(select 1 from corpus.repository_module where id=new.module_id and repository_id=new.repository_id and tenant_id=new.tenant_id) then raise exception 'file module belongs to another repository'; end if;
 return new;
end $$;
create trigger repository_file_lineage before insert or update on corpus.repository_file for each row execute function corpus.check_repository_lineage();
create function temporal.admit_support(p_segment uuid,p_occurrence uuid,p_claim uuid,p_locator uuid,p_role text default 'supports') returns uuid language plpgsql security definer set search_path='' as $$
declare result uuid;
begin
 insert into evidence.segment_support(segment_id,event_occurrence_id,claim_id,locator_id,role) values(p_segment,p_occurrence,p_claim,p_locator,p_role) returning id into result;return result;
end $$;
create function temporal.withdraw_support(p_support uuid) returns void language plpgsql security definer set search_path='' as $$
begin
 update evidence.segment_support set k_to=temporal.current_k() where id=p_support and tenant_id=util.current_tenant_id() and k_to is null;if not found then raise exception 'support not found';end if;
end $$;
revoke all on function temporal.admit_support(uuid,uuid,uuid,uuid,text),temporal.withdraw_support(uuid),corpus.check_receipt_tenant(),corpus.check_repository_lineage(),content.guard_summary_content(),content.check_summary_sources(),content.check_document_work() from public,anon,authenticated,service_role,pipeline_agent,verifier_agent,app_reader;
grant execute on function temporal.admit_support(uuid,uuid,uuid,uuid,text),temporal.withdraw_support(uuid) to executor_service;


do $$ declare r record;begin
 for r in select inhrelid::regclass name from pg_inherits where inhparent='retrieval.vector_item_embedding_1536'::regclass loop
 execute format('alter table %s enable row level security',r.name);
 execute format('revoke all on %s from public,anon,authenticated,app_reader',r.name);
 end loop;
end $$;
revoke all on function corpus.check_relationship_properties(),taxonomy.enforce_term_target_scope() from public,anon,authenticated;


revoke all on function api.entity_rows(),api.entity_aliases(uuid),api.current_fact_rows(),api.current_relationship_rows(),api.current_event_rows() from public,anon;
grant execute on function api.entity_rows(),api.entity_aliases(uuid),api.current_fact_rows(),api.current_relationship_rows(),api.current_event_rows() to app_reader,authenticated,executor_service,pipeline_agent,verifier_agent,control_plane,service_role;
grant select on api.entities,api.current_facts,api.current_relationships,api.events_current to app_reader,authenticated;


do $$ declare t text;begin
 foreach t in array array['evidence.source_query','evidence.provider_result','evidence.source_encounter','evidence.extraction_run','evidence.extraction_record','evidence.attribution','evidence.claim_subject','evidence.claim_record','content.document_summary_source'] loop
 execute format('create trigger km_immutable before update or delete on %s for each row execute function util.reject_mutation()',t);
 execute format('revoke update,delete on %s from pipeline_agent,executor_service',t);
 end loop;
end $$;

commit;
